<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Mursalat</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 77-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْمُرْسَلَـٰتِ</span><span class="en second ltr" dir="ltr">By the ones sent forth,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عُرْفًا</span><span class="en second ltr" dir="ltr">one after another,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱلْعَـٰصِفَـٰتِ</span><span class="en second ltr" dir="ltr">And the winds that blow</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَصْفًا</span><span class="en second ltr" dir="ltr">violently,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلنَّـٰشِرَٲتِ</span><span class="en second ltr" dir="ltr">And the ones that scatter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَشْرًا</span><span class="en second ltr" dir="ltr">far and wide,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱلْفَـٰرِقَـٰتِ</span><span class="en second ltr" dir="ltr">And those who separate</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَرْقًا</span><span class="en second ltr" dir="ltr">(by the) Criterion,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱلْمُلْقِيَـٰتِ</span><span class="en second ltr" dir="ltr">And those who bring down</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِكْرًا</span><span class="en second ltr" dir="ltr">(the) Reminder,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عُذْرًا</span><span class="en second ltr" dir="ltr">(As) justification</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْ</span><span class="en second ltr" dir="ltr">or</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُذْرًا</span><span class="en second ltr" dir="ltr">warning,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّمَا</span><span class="en second ltr" dir="ltr">Indeed, what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُوعَدُونَ</span><span class="en second ltr" dir="ltr">you are promised</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَوَٲقِعٌ</span><span class="en second ltr" dir="ltr">will surely occur.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَإِذَا</span><span class="en second ltr" dir="ltr">So when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنُّجُومُ</span><span class="en second ltr" dir="ltr">the stars</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طُمِسَتْ</span><span class="en second ltr" dir="ltr">are obliterated,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّمَآءُ</span><span class="en second ltr" dir="ltr">the heaven</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فُرِجَتْ</span><span class="en second ltr" dir="ltr">is cleft asunder,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجِبَالُ</span><span class="en second ltr" dir="ltr">the mountains</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُسِفَتْ</span><span class="en second ltr" dir="ltr">are blown away,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرُّسُلُ</span><span class="en second ltr" dir="ltr">the Messengers</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُقِّتَتْ</span><span class="en second ltr" dir="ltr">are gathered to their appointed time.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِأَىِّ</span><span class="en second ltr" dir="ltr">For what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمٍ</span><span class="en second ltr" dir="ltr">Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُجِّلَتْ</span><span class="en second ltr" dir="ltr">are (these) postponed?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِيَوْمِ</span><span class="en second ltr" dir="ltr">For (the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَصْلِ</span><span class="en second ltr" dir="ltr">(of) Judgment.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">will make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَصْلِ</span><span class="en second ltr" dir="ltr">(of) the Judgment?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Did not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُهْلِكِ</span><span class="en second ltr" dir="ltr">We destroy</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَوَّلِينَ</span><span class="en second ltr" dir="ltr">the former (people)?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُتْبِعُهُمُ</span><span class="en second ltr" dir="ltr">We follow them up</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَخِرِينَ</span><span class="en second ltr" dir="ltr">(with) the later ones.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَٲلِكَ</span><span class="en second ltr" dir="ltr">Thus</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَفْعَلُ</span><span class="en second ltr" dir="ltr">We deal</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْمُجْرِمِينَ</span><span class="en second ltr" dir="ltr">with the criminals.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Did not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَخْلُقكُّم</span><span class="en second ltr" dir="ltr">We create you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِّن</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّآءٍ</span><span class="en second ltr" dir="ltr">a water</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّهِينٍ</span><span class="en second ltr" dir="ltr">despicable?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَجَعَلْنَـٰهُ</span><span class="en second ltr" dir="ltr">Then We placed it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَرَارٍ</span><span class="en second ltr" dir="ltr">an abode</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّكِينٍ</span><span class="en second ltr" dir="ltr">safe</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">For</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدَرٍ</span><span class="en second ltr" dir="ltr">a period</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّعْلُومٍ</span><span class="en second ltr" dir="ltr">known.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-23" id="23" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَقَدَرْنَا</span><span class="en second ltr" dir="ltr">So We measured,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَنِعْمَ</span><span class="en second ltr" dir="ltr">and Best</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقَـٰدِرُونَ</span><span class="en second ltr" dir="ltr">(are We to) measure!</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-24" id="24" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-25" id="25" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Have not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَجْعَلِ</span><span class="en second ltr" dir="ltr">We made</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضَ</span><span class="en second ltr" dir="ltr">the earth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كِفَاتًا</span><span class="en second ltr" dir="ltr">a receptacle</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-26" id="26" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحْيَآءً</span><span class="en second ltr" dir="ltr">(For the) living</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمْوَٲتًا</span><span class="en second ltr" dir="ltr">and (the) dead,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-27" id="27" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَجَعَلْنَا</span><span class="en second ltr" dir="ltr">And We made</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَوَٲسِىَ</span><span class="en second ltr" dir="ltr">firmly set mountains</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَـٰمِخَـٰتٍ</span><span class="en second ltr" dir="ltr">lofty,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَسْقَيْنَـٰكُم</span><span class="en second ltr" dir="ltr">and We gave you to drink</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّآءً</span><span class="en second ltr" dir="ltr">water -</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فُرَاتًا</span><span class="en second ltr" dir="ltr">sweet?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>27<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-28" id="28" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>28<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-29" id="29" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنطَلِقُوٓاْ</span><span class="en second ltr" dir="ltr">`Proceed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُنتُم</span><span class="en second ltr" dir="ltr">you used</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهِۦ</span><span class="en second ltr" dir="ltr">in it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُكَذِّبُونَ</span><span class="en second ltr" dir="ltr">(to) deny,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>29<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-30" id="30" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنطَلِقُوٓاْ</span><span class="en second ltr" dir="ltr">Proceed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ظِلٍّ</span><span class="en second ltr" dir="ltr">a shadow</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِى ثَلَـٰثِ</span><span class="en second ltr" dir="ltr">having three</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شُعَبٍ</span><span class="en second ltr" dir="ltr">columns</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>30<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-31" id="31" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّا</span><span class="en second ltr" dir="ltr">No</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ظَلِيلٍ</span><span class="en second ltr" dir="ltr">cool shade</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُغْنِى</span><span class="en second ltr" dir="ltr">availing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنَ</span><span class="en second ltr" dir="ltr">against</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهَبِ</span><span class="en second ltr" dir="ltr">the flame.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>31<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-32" id="32" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهَا</span><span class="en second ltr" dir="ltr">Indeed, it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَرْمِى</span><span class="en second ltr" dir="ltr">throws up</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِشَرَرٍ</span><span class="en second ltr" dir="ltr">sparks</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَٱلْقَصْرِ</span><span class="en second ltr" dir="ltr">as the fortress,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>32<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-33" id="33" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَأَنَّهُۥ</span><span class="en second ltr" dir="ltr">As if they (were)</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جِمَـٰلَتٌ</span><span class="en second ltr" dir="ltr">camels</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صُفْرٌ</span><span class="en second ltr" dir="ltr">yellow.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>33<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-34" id="34" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>34<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-35" id="35" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَـٰذَا</span><span class="en second ltr" dir="ltr">This</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is) a Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَنطِقُونَ</span><span class="en second ltr" dir="ltr">they will speak,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>35<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-36" id="36" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُؤْذَنُ</span><span class="en second ltr" dir="ltr">will it be permitted</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُمْ</span><span class="en second ltr" dir="ltr">for them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَيَعْتَذِرُونَ</span><span class="en second ltr" dir="ltr">to make excuses.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>36<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-37" id="37" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>37<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-38" id="38" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَـٰذَا</span><span class="en second ltr" dir="ltr">This</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَصْلِ‌ۖ</span><span class="en second ltr" dir="ltr">(of) Judgment;</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَمَعْنَـٰكُمْ</span><span class="en second ltr" dir="ltr">We have gathered you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأَوَّلِينَ</span><span class="en second ltr" dir="ltr">and the former (people).</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>38<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-39" id="39" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَإِن</span><span class="en second ltr" dir="ltr">So if</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَانَ</span><span class="en second ltr" dir="ltr">is</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَكُمْ</span><span class="en second ltr" dir="ltr">for you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْدٌ</span><span class="en second ltr" dir="ltr">a plan,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَكِيدُونِ</span><span class="en second ltr" dir="ltr">then plan against Me.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>39<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-40" id="40" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>40<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-41" id="41" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُتَّقِينَ</span><span class="en second ltr" dir="ltr">the righteous</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(will be) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ظِلَـٰلٍ</span><span class="en second ltr" dir="ltr">shades</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَعُيُونٍ</span><span class="en second ltr" dir="ltr">and springs,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>41<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-42" id="42" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَفَوَٲكِهَ</span><span class="en second ltr" dir="ltr">And fruits</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِمَّا</span><span class="en second ltr" dir="ltr">from what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَشْتَهُونَ</span><span class="en second ltr" dir="ltr">they desire.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>42<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-43" id="43" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُلُواْ</span><span class="en second ltr" dir="ltr">`Eat</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱشْرَبُواْ</span><span class="en second ltr" dir="ltr">and drink</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَنِيٓـــَٔۢا</span><span class="en second ltr" dir="ltr">(in) satisfaction</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِمَا</span><span class="en second ltr" dir="ltr">for what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُنتُمْ</span><span class="en second ltr" dir="ltr">you used</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَعْمَلُونَ</span><span class="en second ltr" dir="ltr">(to) do.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>43<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-44" id="44" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّا</span><span class="en second ltr" dir="ltr">Indeed, We</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَٲلِكَ</span><span class="en second ltr" dir="ltr">thus</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَجْزِى</span><span class="en second ltr" dir="ltr">reward</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُحْسِنِينَ</span><span class="en second ltr" dir="ltr">the good-doers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>44<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-45" id="45" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>45<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-46" id="46" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُلُواْ</span><span class="en second ltr" dir="ltr">Eat</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَمَتَّعُواْ</span><span class="en second ltr" dir="ltr">and enjoy yourselves</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَلِيلاً</span><span class="en second ltr" dir="ltr">a little;</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّكُم</span><span class="en second ltr" dir="ltr">indeed, you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّجْرِمُونَ</span><span class="en second ltr" dir="ltr">(are) criminals.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>46<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-47" id="47" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>47<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-48" id="48" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قِيلَ</span><span class="en second ltr" dir="ltr">it is said</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُمُ</span><span class="en second ltr" dir="ltr">to them,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱرْكَعُواْ</span><span class="en second ltr" dir="ltr">`Bow`,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرْكَعُونَ</span><span class="en second ltr" dir="ltr">they bow.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>48<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-49" id="49" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْمُكَذِّبِينَ</span><span class="en second ltr" dir="ltr">to the deniers.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>49<span class="icon rightBracket"> </span></span></p>
<p class="ayah 77-50" id="50" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَبِأَىِّ</span><span class="en second ltr" dir="ltr">Then in what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَدِيثِۭ</span><span class="en second ltr" dir="ltr">statement</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَعْدَهُۥ</span><span class="en second ltr" dir="ltr">after it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُؤْمِنُونَ</span><span class="en second ltr" dir="ltr">will they believe?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>50<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

