<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Qariah</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 101-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقَارِعَةُ</span><span class="en second ltr" dir="ltr">The Striking Calamity!</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">What</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقَارِعَةُ</span><span class="en second ltr" dir="ltr">(is) the Striking Calamity?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">will make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقَارِعَةُ</span><span class="en second ltr" dir="ltr">(is) the Striking Calamity?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَ</span><span class="en second ltr" dir="ltr">(The) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَكُونُ</span><span class="en second ltr" dir="ltr">will be</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنَّاسُ</span><span class="en second ltr" dir="ltr">the mankind</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَٱلْفَرَاشِ</span><span class="en second ltr" dir="ltr">like moths,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَبْثُوثِ</span><span class="en second ltr" dir="ltr">scattered,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَكُونُ</span><span class="en second ltr" dir="ltr">And will be</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجِبَالُ</span><span class="en second ltr" dir="ltr">the mountains</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَٱلْعِهْنِ</span><span class="en second ltr" dir="ltr">like wool,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَنفُوشِ</span><span class="en second ltr" dir="ltr">fluffed up.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَمَّا</span><span class="en second ltr" dir="ltr">Then as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">(him) whose</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثَقُلَتْ</span><span class="en second ltr" dir="ltr">are heavy</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَوَٲزِينُهُۥ</span><span class="en second ltr" dir="ltr">his scales,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَهُوَ</span><span class="en second ltr" dir="ltr">Then he</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(will be) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عِيشَةٍ</span><span class="en second ltr" dir="ltr">a life,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَّاضِيَةٍ</span><span class="en second ltr" dir="ltr">pleasant.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّا</span><span class="en second ltr" dir="ltr">But as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَنْ</span><span class="en second ltr" dir="ltr">(him) whose</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَفَّتْ</span><span class="en second ltr" dir="ltr">are light</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَوَٲزِينُهُۥ</span><span class="en second ltr" dir="ltr">his scales,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأُمُّهُۥ</span><span class="en second ltr" dir="ltr">His abode</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَاوِيَةٌ</span><span class="en second ltr" dir="ltr">(will be the) Pit.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">will make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هِيَهْ</span><span class="en second ltr" dir="ltr">it is?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 101-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَارٌ</span><span class="en second ltr" dir="ltr">A Fire,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَامِيَةُۢ</span><span class="en second ltr" dir="ltr">intensely hot.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

