<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/vocabulary.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Ash-Shams</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 91-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلشَّمْسِ</span><span class="en second ltr" dir="ltr">By the sun</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَضُحَـٰهَا</span><span class="en second ltr" dir="ltr">and its brightness,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْقَمَرِ</span><span class="en second ltr" dir="ltr">And the moon</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَلَـٰهَا</span><span class="en second ltr" dir="ltr">it follows it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلنَّهَارِ</span><span class="en second ltr" dir="ltr">And the day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَلَّـٰهَا</span><span class="en second ltr" dir="ltr">it displays it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّيْلِ</span><span class="en second ltr" dir="ltr">And the night</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَغْشَـٰهَا</span><span class="en second ltr" dir="ltr">it covers it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلسَّمَآءِ</span><span class="en second ltr" dir="ltr">And the heaven</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and He Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَنَـٰهَا</span><span class="en second ltr" dir="ltr">constructed it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأَرْضِ</span><span class="en second ltr" dir="ltr">And the earth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and He Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طَحَـٰهَا</span><span class="en second ltr" dir="ltr">spread it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَنَفْسٍ</span><span class="en second ltr" dir="ltr">And (the) soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and He Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَوَّٮٰهَا</span><span class="en second ltr" dir="ltr">proportioned it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَلْهَمَهَا</span><span class="en second ltr" dir="ltr">And He inspired it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فُجُورَهَا</span><span class="en second ltr" dir="ltr">(to understand) what is wrong for it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَقْوَٮٰهَا</span><span class="en second ltr" dir="ltr">and what is right for it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدْ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَفْلَحَ</span><span class="en second ltr" dir="ltr">he succeeds</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">زَكَّـٰهَا</span><span class="en second ltr" dir="ltr">purifies it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَقَدْ</span><span class="en second ltr" dir="ltr">And indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَابَ</span><span class="en second ltr" dir="ltr">he fails</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">دَسَّـٰهَا</span><span class="en second ltr" dir="ltr">corrupts it.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَّبَتْ</span><span class="en second ltr" dir="ltr">Denied</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثَمُودُ</span><span class="en second ltr" dir="ltr">Thamud</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِطَغْوَٮٰهَآ</span><span class="en second ltr" dir="ltr">by their transgression,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذِ</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنۢبَعَثَ</span><span class="en second ltr" dir="ltr">(was) sent forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَشْقَـٰهَا</span><span class="en second ltr" dir="ltr">(the) most wicked of them.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَقَالَ</span><span class="en second ltr" dir="ltr">But said</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُمْ</span><span class="en second ltr" dir="ltr">to them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَسُولُ</span><span class="en second ltr" dir="ltr">(the) Messenger</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهِ</span><span class="en second ltr" dir="ltr">(of) Allah,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَاقَةَ</span><span class="en second ltr" dir="ltr">`(It is the) she-camel</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهِ</span><span class="en second ltr" dir="ltr">(of) Allah</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَسُقْيَـٰهَا</span><span class="en second ltr" dir="ltr">and her drink.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَكَذَّبُوهُ</span><span class="en second ltr" dir="ltr">But they denied him,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَعَقَرُوهَا</span><span class="en second ltr" dir="ltr">and they hamstrung her.</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَدَمْدَمَ</span><span class="en second ltr" dir="ltr">So destroyed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِمْ</span><span class="en second ltr" dir="ltr">them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّهُم</span><span class="en second ltr" dir="ltr">their Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِذَنۢبِهِمْ</span><span class="en second ltr" dir="ltr">for their sin</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَوَّٮٰهَا</span><span class="en second ltr" dir="ltr">and leveled them.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 91-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَخَافُ</span><span class="en second ltr" dir="ltr">He fears</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عُقْبَـٰهَا</span><span class="en second ltr" dir="ltr">its consequences.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

