<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Fatihah</p>
				</div>
				<div class="ayahs rtl" dir="rtl">
				<p class="ayah 1-1" id="1"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِسْمِ</span><span class="en second ltr" dir="ltr">In (the) name</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهِ</span><span class="en second ltr" dir="ltr">(of) Allah,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرَّحْمَـٰنِ</span><span class="en second ltr" dir="ltr">the Most Gracious,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرَّحِيمِ</span><span class="en second ltr" dir="ltr">the Most Merciful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-2" id="2"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحَمْدُ</span><span class="en second ltr" dir="ltr">All praises and thanks</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِلَّهِ</span><span class="en second ltr" dir="ltr">(be) to Allah,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّ</span><span class="en second ltr" dir="ltr">(the) Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَـٰلَمِينَ</span><span class="en second ltr" dir="ltr">(of all) the worlds.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-3" id="3"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرَّحْمَـٰنِ</span><span class="en second ltr" dir="ltr">The Most Gracious,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرَّحِيمِ</span><span class="en second ltr" dir="ltr">the Most Merciful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-4" id="4"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَـٰلِكِ</span><span class="en second ltr" dir="ltr">Master</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمِ</span><span class="en second ltr" dir="ltr">(of the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلدِّينِ</span><span class="en second ltr" dir="ltr">(of) [the] Judgment.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-5" id="5"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِيَّاكَ</span><span class="en second ltr" dir="ltr">You Alone</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَعْبُدُ</span><span class="en second ltr" dir="ltr">we worship,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِيَّاكَ</span><span class="en second ltr" dir="ltr">and You Alone</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَسْتَعِينُ</span><span class="en second ltr" dir="ltr">we ask for help.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-6" id="6"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱهْدِنَا</span><span class="en second ltr" dir="ltr">Guide us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصِّرَٲطَ</span><span class="en second ltr" dir="ltr">(to) the path,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُسْتَقِيمَ</span><span class="en second ltr" dir="ltr">the straight.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
				<p class="ayah 1-7" id="7"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صِرَٲطَ</span><span class="en second ltr" dir="ltr">(The) path</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">(of) those</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنْعَمْتَ</span><span class="en second ltr" dir="ltr">You have bestowed (Your) Favors</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِمْ</span><span class="en second ltr" dir="ltr">on them,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">غَيْرِ</span><span class="en second ltr" dir="ltr">not (of)</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَغْضُوبِ</span><span class="en second ltr" dir="ltr">those who earned (Your) wrath</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِمْ</span><span class="en second ltr" dir="ltr">on themselves,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلضَّآلِّينَ</span><span class="en second ltr" dir="ltr">(of) those who go astray.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
				</div>
			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

