<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Fajr</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 89-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْفَجْرِ</span><span class="en second ltr" dir="ltr">By the dawn,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَيَالٍ</span><span class="en second ltr" dir="ltr">And the nights</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَشْرٍ</span><span class="en second ltr" dir="ltr">ten.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلشَّفْعِ</span><span class="en second ltr" dir="ltr">And the even</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْوَتْرِ</span><span class="en second ltr" dir="ltr">and the odd,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّيْلِ</span><span class="en second ltr" dir="ltr">And the night</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَسْرِ</span><span class="en second ltr" dir="ltr">it passes.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَلْ</span><span class="en second ltr" dir="ltr">Is</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَٲلِكَ</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَسَمٌ</span><span class="en second ltr" dir="ltr">an oath</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّذِى حِجْرٍ</span><span class="en second ltr" dir="ltr">for those who understand?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Do not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَرَ</span><span class="en second ltr" dir="ltr">you see</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْفَ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَعَلَ</span><span class="en second ltr" dir="ltr">dealt</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِعَادٍ</span><span class="en second ltr" dir="ltr">with Aad,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِرَمَ</span><span class="en second ltr" dir="ltr">Iram</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَاتِ ٱلْعِمَادِ</span><span class="en second ltr" dir="ltr">possessors (of) lofty pillars,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّتِى</span><span class="en second ltr" dir="ltr">Which</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَمْ</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُخْلَقْ</span><span class="en second ltr" dir="ltr">had been created</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِثْلُهَا</span><span class="en second ltr" dir="ltr">like them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبِلَـٰدِ</span><span class="en second ltr" dir="ltr">the cities,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَثَمُودَ</span><span class="en second ltr" dir="ltr">And Thamud,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَابُواْ</span><span class="en second ltr" dir="ltr">carved out</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصَّخْرَ</span><span class="en second ltr" dir="ltr">the rocks</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْوَادِ</span><span class="en second ltr" dir="ltr">in the valley,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَفِرْعَوْنَ</span><span class="en second ltr" dir="ltr">And Firaun,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِى ٱلْأَوْتَادِ</span><span class="en second ltr" dir="ltr">owner of stakes?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طَغَوْاْ</span><span class="en second ltr" dir="ltr">transgressed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبِلَـٰدِ</span><span class="en second ltr" dir="ltr">the lands,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَكْثَرُواْ</span><span class="en second ltr" dir="ltr">And made much</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَسَادَ</span><span class="en second ltr" dir="ltr">corruption.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَصَبَّ</span><span class="en second ltr" dir="ltr">So poured</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِمْ</span><span class="en second ltr" dir="ltr">on them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَوْطَ</span><span class="en second ltr" dir="ltr">scourge</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَذَابٍ</span><span class="en second ltr" dir="ltr">(of) punishment.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبَّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَبِٱلْمِرْصَادِ</span><span class="en second ltr" dir="ltr">(is) surely Ever Watchful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَمَّا</span><span class="en second ltr" dir="ltr">And as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">man,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا مَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱبْتَلَـٰهُ</span><span class="en second ltr" dir="ltr">tries him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّهُۥ</span><span class="en second ltr" dir="ltr">his Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَكْرَمَهُۥ</span><span class="en second ltr" dir="ltr">and is generous to him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَنَعَّمَهُۥ</span><span class="en second ltr" dir="ltr">and favors him,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَيَقُولُ</span><span class="en second ltr" dir="ltr">he says,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّىٓ</span><span class="en second ltr" dir="ltr">`My Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَكْرَمَنِ</span><span class="en second ltr" dir="ltr">has honored me.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّآ</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا مَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱبْتَلَـٰهُ</span><span class="en second ltr" dir="ltr">He tries him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَقَدَرَ</span><span class="en second ltr" dir="ltr">and restricts</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِ</span><span class="en second ltr" dir="ltr">for him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رِزْقَهُۥ</span><span class="en second ltr" dir="ltr">his provision,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَيَقُولُ</span><span class="en second ltr" dir="ltr">then he says</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّىٓ</span><span class="en second ltr" dir="ltr">`My Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَهَـٰنَنِ</span><span class="en second ltr" dir="ltr">(has) humiliated me.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا‌ۖ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَل</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُكْرِمُونَ</span><span class="en second ltr" dir="ltr">you honor</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْيَتِيمَ</span><span class="en second ltr" dir="ltr">the orphan,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَحَـٰٓضُّونَ</span><span class="en second ltr" dir="ltr">you feel the urge</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طَعَامِ</span><span class="en second ltr" dir="ltr">feed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمِسْكِينِ</span><span class="en second ltr" dir="ltr">the poor.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَأْكُلُونَ</span><span class="en second ltr" dir="ltr">And you consume</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلتُّرَاثَ</span><span class="en second ltr" dir="ltr">the inheritance</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَكْلاً لَّمًّا</span><span class="en second ltr" dir="ltr">devouring altogether,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتُحِبُّونَ</span><span class="en second ltr" dir="ltr">And you love</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَالَ</span><span class="en second ltr" dir="ltr">wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حُبًّا</span><span class="en second ltr" dir="ltr">(with) love</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَمًّا</span><span class="en second ltr" dir="ltr">exceeding.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّآ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">دُكَّتِ</span><span class="en second ltr" dir="ltr">is leveled</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضُ</span><span class="en second ltr" dir="ltr">the earth,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">دَكًّا دَكًّا</span><span class="en second ltr" dir="ltr">pounded and crushed,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَجَآءَ</span><span class="en second ltr" dir="ltr">And comes</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْمَلَكُ</span><span class="en second ltr" dir="ltr">and the Angels,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَفًّا صَفًّا</span><span class="en second ltr" dir="ltr">rank upon rank,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-23" id="23" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَجِاْىٓءَ</span><span class="en second ltr" dir="ltr">And is brought,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذِۭ</span><span class="en second ltr" dir="ltr">that Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِجَهَنَّمَ‌ۚ</span><span class="en second ltr" dir="ltr">Hell.</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">That Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتَذَكَّرُ</span><span class="en second ltr" dir="ltr">will remember</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">man,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَنَّىٰ</span><span class="en second ltr" dir="ltr">but how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُ</span><span class="en second ltr" dir="ltr">(will be) for him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلذِّكْرَىٰ</span><span class="en second ltr" dir="ltr">the remembrance?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-24" id="24" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَقُولُ</span><span class="en second ltr" dir="ltr">He will say,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَـٰلَيْتَنِى</span><span class="en second ltr" dir="ltr">`O! I wish</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدَّمْتُ</span><span class="en second ltr" dir="ltr">I had sent forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِحَيَاتِى</span><span class="en second ltr" dir="ltr">for my life.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-25" id="25" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَيَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">So that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُعَذِّبُ</span><span class="en second ltr" dir="ltr">will punish,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَذَابَهُۥٓ</span><span class="en second ltr" dir="ltr">(as) His punishment</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحَدٌ</span><span class="en second ltr" dir="ltr">anyone.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-26" id="26" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُوثِقُ</span><span class="en second ltr" dir="ltr">will bind</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَثَاقَهُۥٓ</span><span class="en second ltr" dir="ltr">(as) His binding</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحَدٌ</span><span class="en second ltr" dir="ltr">anyone.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-27" id="27" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَـٰٓأَيَّتُهَا ٱلنَّفْسُ</span><span class="en second ltr" dir="ltr">`O soul!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُطْمَئِنَّةُ</span><span class="en second ltr" dir="ltr">who is satisfied,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>27<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-28" id="28" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱرْجِعِىٓ</span><span class="en second ltr" dir="ltr">Return</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكِ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَاضِيَةً</span><span class="en second ltr" dir="ltr">well pleased,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّرْضِيَّةً</span><span class="en second ltr" dir="ltr">and pleasing.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>28<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-29" id="29" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱدْخُلِى</span><span class="en second ltr" dir="ltr">So enter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">among</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عِبَـٰدِى</span><span class="en second ltr" dir="ltr">My slaves,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>29<span class="icon rightBracket"> </span></span></p>
<p class="ayah 89-30" id="30" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱدْخُلِى</span><span class="en second ltr" dir="ltr">And enter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَنَّتِى</span><span class="en second ltr" dir="ltr">My Paradise.`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>30<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

