<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/vocabulary.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Ad-Duha</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 93-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلضُّحَىٰ</span><span class="en second ltr" dir="ltr">By the morning brightness,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّيْلِ</span><span class="en second ltr" dir="ltr">And the night</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَجَىٰ</span><span class="en second ltr" dir="ltr">it covers with darkness,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَدَّعَكَ</span><span class="en second ltr" dir="ltr">has forsaken you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَلَىٰ</span><span class="en second ltr" dir="ltr">He is displeased,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَلْأَخِرَةُ</span><span class="en second ltr" dir="ltr">And surely the Hereafter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَيْرٌ</span><span class="en second ltr" dir="ltr">(is) better</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّكَ</span><span class="en second ltr" dir="ltr">for you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنَ</span><span class="en second ltr" dir="ltr">than</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأُولَىٰ</span><span class="en second ltr" dir="ltr">the first.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَسَوْفَ</span><span class="en second ltr" dir="ltr">And soon</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُعْطِيكَ</span><span class="en second ltr" dir="ltr">will give you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَتَرْضَىٰٓ</span><span class="en second ltr" dir="ltr">then you will be satisfied.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Did not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَجِدْكَ</span><span class="en second ltr" dir="ltr">He find you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتِيمًا</span><span class="en second ltr" dir="ltr">an orphan</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَـَٔـاوَىٰ</span><span class="en second ltr" dir="ltr">and gave shelter?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَوَجَدَكَ</span><span class="en second ltr" dir="ltr">And He found you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ضَآلاًّ</span><span class="en second ltr" dir="ltr">lost,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَهَدَىٰ</span><span class="en second ltr" dir="ltr">so He guided,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَوَجَدَكَ</span><span class="en second ltr" dir="ltr">And He found you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَآئِلاً</span><span class="en second ltr" dir="ltr">in need,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَغْنَىٰ</span><span class="en second ltr" dir="ltr">so He made self-sufficient.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَمَّا</span><span class="en second ltr" dir="ltr">So as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْيَتِيمَ</span><span class="en second ltr" dir="ltr">the orphan,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَا</span><span class="en second ltr" dir="ltr">then (do) not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَقْهَرْ</span><span class="en second ltr" dir="ltr">oppress,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّا</span><span class="en second ltr" dir="ltr">And as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّآئِلَ</span><span class="en second ltr" dir="ltr">him who asks,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَا</span><span class="en second ltr" dir="ltr">then (do) not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَنْهَرْ</span><span class="en second ltr" dir="ltr">repel,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 93-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّا</span><span class="en second ltr" dir="ltr">But as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِنِعْمَةِ</span><span class="en second ltr" dir="ltr">(the) Favor</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">(of) your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَحَدِّثْ</span><span class="en second ltr" dir="ltr">narrate.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

