<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Qiyamah</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 75-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَآ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُقْسِمُ</span><span class="en second ltr" dir="ltr">I swear</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِيَوْمِ</span><span class="en second ltr" dir="ltr">by (the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقِيَـٰمَةِ</span><span class="en second ltr" dir="ltr">(of) the Resurrection.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَآ</span><span class="en second ltr" dir="ltr">And nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُقْسِمُ</span><span class="en second ltr" dir="ltr">I swear</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلنَّفْسِ</span><span class="en second ltr" dir="ltr">by the soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّوَّامَةِ</span><span class="en second ltr" dir="ltr">self-accusing.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيَحْسَبُ</span><span class="en second ltr" dir="ltr">Does think</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">[the] man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَّن</span><span class="en second ltr" dir="ltr">that not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَّجْمَعَ</span><span class="en second ltr" dir="ltr">We will assemble</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عِظَامَهُۥ</span><span class="en second ltr" dir="ltr">his bones?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلَىٰ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَـٰدِرِينَ</span><span class="en second ltr" dir="ltr">[We are] able</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰٓ</span><span class="en second ltr" dir="ltr">on</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُّسَوِّىَ</span><span class="en second ltr" dir="ltr">We can restore</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَنَانَهُۥ</span><span class="en second ltr" dir="ltr">his fingertips.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلْ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُرِيدُ</span><span class="en second ltr" dir="ltr">Desires</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">[the] man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِيَفْجُرَ</span><span class="en second ltr" dir="ltr">to give (the) lie</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمَامَهُۥ</span><span class="en second ltr" dir="ltr">(to) what is before him.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَسْــَٔلُ</span><span class="en second ltr" dir="ltr">He asks,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيَّانَ</span><span class="en second ltr" dir="ltr">`When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقِيَـٰمَةِ</span><span class="en second ltr" dir="ltr">(of) the Resurrection?`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَإِذَا</span><span class="en second ltr" dir="ltr">So when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَرِقَ</span><span class="en second ltr" dir="ltr">is dazzled</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبَصَرُ</span><span class="en second ltr" dir="ltr">the vision,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَخَسَفَ</span><span class="en second ltr" dir="ltr">And becomes dark</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقَمَرُ</span><span class="en second ltr" dir="ltr">the moon,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَجُمِعَ</span><span class="en second ltr" dir="ltr">And are joined</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلشَّمْسُ</span><span class="en second ltr" dir="ltr">the sun</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْقَمَرُ</span><span class="en second ltr" dir="ltr">and the moon,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَقُولُ</span><span class="en second ltr" dir="ltr">Will say</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">[the] man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيْنَ</span><span class="en second ltr" dir="ltr">`Where</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَفَرُّ</span><span class="en second ltr" dir="ltr">(is) the escape?`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">By no means!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">(There is) no</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَزَرَ</span><span class="en second ltr" dir="ltr">refuge.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">To</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">your Lord,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُسْتَقَرُّ</span><span class="en second ltr" dir="ltr">(is) the place of rest.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُنَبَّؤُاْ</span><span class="en second ltr" dir="ltr">Will be informed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">[the] man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذِۭ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِمَا</span><span class="en second ltr" dir="ltr">of what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدَّمَ</span><span class="en second ltr" dir="ltr">he sent forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَخَّرَ</span><span class="en second ltr" dir="ltr">and kept back.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلِ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">[The] man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰ</span><span class="en second ltr" dir="ltr">against</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَفْسِهِۦ</span><span class="en second ltr" dir="ltr">himself</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَصِيرَةٌ</span><span class="en second ltr" dir="ltr">(will be) a witness.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَوْ</span><span class="en second ltr" dir="ltr">Even if</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلْقَىٰ</span><span class="en second ltr" dir="ltr">he presents</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَعَاذِيرَهُۥ</span><span class="en second ltr" dir="ltr">his excuses.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُحَرِّكْ</span><span class="en second ltr" dir="ltr">move</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهِۦ</span><span class="en second ltr" dir="ltr">with it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِسَانَكَ</span><span class="en second ltr" dir="ltr">your tongue</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِتَعْجَلَ</span><span class="en second ltr" dir="ltr">to hasten</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهِۦٓ</span><span class="en second ltr" dir="ltr">with it.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْنَا</span><span class="en second ltr" dir="ltr">upon Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَمْعَهُۥ</span><span class="en second ltr" dir="ltr">(is) its collection</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَقُرْءَانَهُۥ</span><span class="en second ltr" dir="ltr">and its recitation.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَرَأْنَـٰهُ</span><span class="en second ltr" dir="ltr">We have recited it,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱتَّبِعْ</span><span class="en second ltr" dir="ltr">then follow</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُرْءَانَهُۥ</span><span class="en second ltr" dir="ltr">its recitation.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْنَا</span><span class="en second ltr" dir="ltr">upon Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَيَانَهُۥ</span><span class="en second ltr" dir="ltr">(is) its explanation.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">No!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلْ</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُحِبُّونَ</span><span class="en second ltr" dir="ltr">you love</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَاجِلَةَ</span><span class="en second ltr" dir="ltr">the immediate,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَذَرُونَ</span><span class="en second ltr" dir="ltr">And leave</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَخِرَةَ</span><span class="en second ltr" dir="ltr">the Hereafter.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وُجُوهٌ</span><span class="en second ltr" dir="ltr">Faces</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَّاضِرَةٌ</span><span class="en second ltr" dir="ltr">(will be) radiant,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-23" id="23" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">Towards</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّهَا</span><span class="en second ltr" dir="ltr">their Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَاظِرَةٌ</span><span class="en second ltr" dir="ltr">looking,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-24" id="24" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَوُجُوهٌ</span><span class="en second ltr" dir="ltr">And faces</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذِۭ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَاسِرَةٌ</span><span class="en second ltr" dir="ltr">(will be) distorted,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-25" id="25" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَظُنُّ</span><span class="en second ltr" dir="ltr">Thinking</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُفْعَلَ</span><span class="en second ltr" dir="ltr">will be done</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهَا</span><span class="en second ltr" dir="ltr">to them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَاقِرَةٌ</span><span class="en second ltr" dir="ltr">backbreaking.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-26" id="26" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّآ</span><span class="en second ltr" dir="ltr">No!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلَغَتِ</span><span class="en second ltr" dir="ltr">it reaches</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلتَّرَاقِىَ</span><span class="en second ltr" dir="ltr">the collar bones</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-27" id="27" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَقِيلَ</span><span class="en second ltr" dir="ltr">And it is said,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَنْۜ</span><span class="en second ltr" dir="ltr">`Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَاقٍ</span><span class="en second ltr" dir="ltr">(will) cure?`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>27<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-28" id="28" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَظَنَّ</span><span class="en second ltr" dir="ltr">And he is certain</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنَّهُ</span><span class="en second ltr" dir="ltr">that it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفِرَاقُ</span><span class="en second ltr" dir="ltr">(is) the parting.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>28<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-29" id="29" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْتَفَّتِ</span><span class="en second ltr" dir="ltr">And is wound,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّاقُ</span><span class="en second ltr" dir="ltr">the leg</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلسَّاقِ</span><span class="en second ltr" dir="ltr">about the leg,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>29<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-30" id="30" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">To</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَسَاقُ</span><span class="en second ltr" dir="ltr">(will be) the driving.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>30<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-31" id="31" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَدَّقَ</span><span class="en second ltr" dir="ltr">he accepted (the) truth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَلَّىٰ</span><span class="en second ltr" dir="ltr">he prayed.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>31<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-32" id="32" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَـٰكِن</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَّبَ</span><span class="en second ltr" dir="ltr">he denied</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَلَّىٰ</span><span class="en second ltr" dir="ltr">and turned away.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>32<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-33" id="33" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَهَبَ</span><span class="en second ltr" dir="ltr">he went</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰٓ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَهْلِهِۦ</span><span class="en second ltr" dir="ltr">his family,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتَمَطَّىٰٓ</span><span class="en second ltr" dir="ltr">swaggering.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>33<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-34" id="34" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْلَىٰ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَكَ</span><span class="en second ltr" dir="ltr">to you,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَوْلَىٰ</span><span class="en second ltr" dir="ltr">and woe!</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>34<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-35" id="35" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْلَىٰ</span><span class="en second ltr" dir="ltr">woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَكَ</span><span class="en second ltr" dir="ltr">to you,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَوْلَىٰٓ</span><span class="en second ltr" dir="ltr">and woe!</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>35<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-36" id="36" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيَحْسَبُ</span><span class="en second ltr" dir="ltr">Does think</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُتْرَكَ</span><span class="en second ltr" dir="ltr">he will be left</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُدًى</span><span class="en second ltr" dir="ltr">neglected?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>36<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-37" id="37" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Was not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَكُ</span><span class="en second ltr" dir="ltr">he</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُطْفَةً</span><span class="en second ltr" dir="ltr">a sperm</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِّن</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّنِىٍّ</span><span class="en second ltr" dir="ltr">semen</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُمْنَىٰ</span><span class="en second ltr" dir="ltr">emitted?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>37<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-38" id="38" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَانَ</span><span class="en second ltr" dir="ltr">he was</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَقَةً</span><span class="en second ltr" dir="ltr">a clinging substance,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَخَلَقَ</span><span class="en second ltr" dir="ltr">then He created</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَوَّىٰ</span><span class="en second ltr" dir="ltr">and proportioned.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>38<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-39" id="39" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَجَعَلَ</span><span class="en second ltr" dir="ltr">Then made</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْهُ</span><span class="en second ltr" dir="ltr">of him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلزَّوْجَيْنِ</span><span class="en second ltr" dir="ltr">two mates,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلذَّكَرَ</span><span class="en second ltr" dir="ltr">(the) male</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأُنثَىٰٓ</span><span class="en second ltr" dir="ltr">and the female.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>39<span class="icon rightBracket"> </span></span></p>
<p class="ayah 75-40" id="40" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَيْسَ</span><span class="en second ltr" dir="ltr">Is not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَٲلِكَ</span><span class="en second ltr" dir="ltr">[that]</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِقَـٰدِرٍ</span><span class="en second ltr" dir="ltr">(He) Able</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰٓ</span><span class="en second ltr" dir="ltr">[over]</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُحْــِۧىَ</span><span class="en second ltr" dir="ltr">give life</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَوْتَىٰ</span><span class="en second ltr" dir="ltr">(to) the dead?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>40<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

