<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Ghashiyah</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 88-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَلْ</span><span class="en second ltr" dir="ltr">Has</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَتَـٰكَ</span><span class="en second ltr" dir="ltr">(there) come to you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَدِيثُ</span><span class="en second ltr" dir="ltr">(the) news</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْغَـٰشِيَةِ</span><span class="en second ltr" dir="ltr">(of) the Overwhelming?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وُجُوهٌ</span><span class="en second ltr" dir="ltr">Faces</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَـٰشِعَةٌ</span><span class="en second ltr" dir="ltr">(will be) humbled,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَامِلَةٌ</span><span class="en second ltr" dir="ltr">Laboring,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَّاصِبَةٌ</span><span class="en second ltr" dir="ltr">exhausted.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَصْلَىٰ</span><span class="en second ltr" dir="ltr">They will burn</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَارًا</span><span class="en second ltr" dir="ltr">(in) a Fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَامِيَةً</span><span class="en second ltr" dir="ltr">intensely hot.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُسْقَىٰ</span><span class="en second ltr" dir="ltr">They will be given to drink</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْ</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَيْنٍ</span><span class="en second ltr" dir="ltr">a spring,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ءَانِيَةٍ</span><span class="en second ltr" dir="ltr">boiling.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّيْسَ</span><span class="en second ltr" dir="ltr">Is not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُمْ</span><span class="en second ltr" dir="ltr">for them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طَعَامٌ</span><span class="en second ltr" dir="ltr">food</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ضَرِيعٍ</span><span class="en second ltr" dir="ltr">a bitter thorny plant,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُسْمِنُ</span><span class="en second ltr" dir="ltr">it nourishes</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُغْنِى</span><span class="en second ltr" dir="ltr">it avails</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">against</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جُوعٍ</span><span class="en second ltr" dir="ltr">hunger.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وُجُوهٌ</span><span class="en second ltr" dir="ltr">Faces</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَّاعِمَةٌ</span><span class="en second ltr" dir="ltr">(will be) joyful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّسَعْيِهَا</span><span class="en second ltr" dir="ltr">With their effort</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَاضِيَةٌ</span><span class="en second ltr" dir="ltr">satisfied,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">In</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَنَّةٍ</span><span class="en second ltr" dir="ltr">a garden</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَالِيَةٍ</span><span class="en second ltr" dir="ltr">elevated.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَسْمَعُ</span><span class="en second ltr" dir="ltr">they will hear</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَـٰغِيَةً</span><span class="en second ltr" dir="ltr">vain talk.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">Therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَيْنٌ</span><span class="en second ltr" dir="ltr">(will be) a spring</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَارِيَةٌ</span><span class="en second ltr" dir="ltr">flowing,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">Therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُرُرٌ</span><span class="en second ltr" dir="ltr">(will be) thrones</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّرْفُوعَةٌ</span><span class="en second ltr" dir="ltr">raised high,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَكْوَابٌ</span><span class="en second ltr" dir="ltr">And cups</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّوْضُوعَةٌ</span><span class="en second ltr" dir="ltr">put in place,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَنَمَارِقُ</span><span class="en second ltr" dir="ltr">And cushions</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَصْفُوفَةٌ</span><span class="en second ltr" dir="ltr">lined up,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَزَرَابِىُّ</span><span class="en second ltr" dir="ltr">And carpets</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَبْثُوثَةٌ</span><span class="en second ltr" dir="ltr">spread out.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَفَلَا</span><span class="en second ltr" dir="ltr">Then do not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَنظُرُونَ</span><span class="en second ltr" dir="ltr">they look</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَى</span><span class="en second ltr" dir="ltr">at</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِبِلِ</span><span class="en second ltr" dir="ltr">the camels,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْفَ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خُلِقَتْ</span><span class="en second ltr" dir="ltr">they are created?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِلَى</span><span class="en second ltr" dir="ltr">And at</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّمَآءِ</span><span class="en second ltr" dir="ltr">the sky,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْفَ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رُفِعَتْ</span><span class="en second ltr" dir="ltr">it is raised?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِلَى</span><span class="en second ltr" dir="ltr">And at</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجِبَالِ</span><span class="en second ltr" dir="ltr">the mountains,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْفَ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُصِبَتْ</span><span class="en second ltr" dir="ltr">they are fixed?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِلَى</span><span class="en second ltr" dir="ltr">And at</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضِ</span><span class="en second ltr" dir="ltr">the earth,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَيْفَ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُطِحَتْ</span><span class="en second ltr" dir="ltr">it is spread out?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَذَكِّرْ</span><span class="en second ltr" dir="ltr">So remind,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّمَآ</span><span class="en second ltr" dir="ltr">only</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنتَ</span><span class="en second ltr" dir="ltr">you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُذَكِّرٌ</span><span class="en second ltr" dir="ltr">(are) a reminder.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّسْتَ</span><span class="en second ltr" dir="ltr">You are not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِم</span><span class="en second ltr" dir="ltr">over them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِمُصَيْطِرٍ</span><span class="en second ltr" dir="ltr">a controller,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-23" id="23" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">whoever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَوَلَّىٰ</span><span class="en second ltr" dir="ltr">turns away</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَكَفَرَ</span><span class="en second ltr" dir="ltr">and disbelieves,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-24" id="24" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَيُعَذِّبُهُ ٱللَّهُ</span><span class="en second ltr" dir="ltr">Then Allah will punish him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَذَابَ</span><span class="en second ltr" dir="ltr">(with) the punishment</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَكْبَرَ</span><span class="en second ltr" dir="ltr">greatest.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-25" id="25" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَيْنَآ</span><span class="en second ltr" dir="ltr">to Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِيَابَهُمْ</span><span class="en second ltr" dir="ltr">(will be) their return,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></span></p>
<p class="ayah 88-26" id="26" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْنَا</span><span class="en second ltr" dir="ltr">upon Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حِسَابَهُم</span><span class="en second ltr" dir="ltr">(is) their account.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

