<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/vocabulary.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Buruj</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 85-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلسَّمَآءِ</span><span class="en second ltr" dir="ltr">By the sky,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَاتِ</span><span class="en second ltr" dir="ltr">containing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبُرُوجِ</span><span class="en second ltr" dir="ltr">the constellations,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْيَوْمِ</span><span class="en second ltr" dir="ltr">And the Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَوْعُودِ</span><span class="en second ltr" dir="ltr">Promised,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَشَاهِدٍ</span><span class="en second ltr" dir="ltr">And (the) witness</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَشْهُودٍ</span><span class="en second ltr" dir="ltr">and what is witnessed,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُتِلَ</span><span class="en second ltr" dir="ltr">Destroyed were</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَصْحَـٰبُ</span><span class="en second ltr" dir="ltr">(the) companions</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأُخْدُودِ</span><span class="en second ltr" dir="ltr">(of) the pit,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنَّارِ</span><span class="en second ltr" dir="ltr">(Of) the fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَاتِ</span><span class="en second ltr" dir="ltr">full</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْوَقُودِ</span><span class="en second ltr" dir="ltr">(of) the fuel,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذْ</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُمْ</span><span class="en second ltr" dir="ltr">they</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهَا</span><span class="en second ltr" dir="ltr">by it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُعُودٌ</span><span class="en second ltr" dir="ltr">(were) sitting,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَهُمْ</span><span class="en second ltr" dir="ltr">And they</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰ</span><span class="en second ltr" dir="ltr">over</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَفْعَلُونَ</span><span class="en second ltr" dir="ltr">they were doing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْمُؤْمِنِينَ</span><span class="en second ltr" dir="ltr">to the believers</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شُهُودٌ</span><span class="en second ltr" dir="ltr">witnesses.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَقَمُواْ</span><span class="en second ltr" dir="ltr">they resented</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْهُمْ</span><span class="en second ltr" dir="ltr">[of] them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّآ</span><span class="en second ltr" dir="ltr">except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُؤْمِنُواْ</span><span class="en second ltr" dir="ltr">they believed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱللَّهِ</span><span class="en second ltr" dir="ltr">in Allah</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَزِيزِ</span><span class="en second ltr" dir="ltr">the All-Mighty,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحَمِيدِ</span><span class="en second ltr" dir="ltr">the Praiseworthy,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The One Who,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُۥ</span><span class="en second ltr" dir="ltr">for Him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُلْكُ</span><span class="en second ltr" dir="ltr">(is) the dominion</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّمَـٰوَٲتِ</span><span class="en second ltr" dir="ltr">(of) the heavens</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأَرْضِ‌ۚ</span><span class="en second ltr" dir="ltr">and the earth;</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱللَّهُ</span><span class="en second ltr" dir="ltr">and Allah</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰ</span><span class="en second ltr" dir="ltr">on</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُلِّ</span><span class="en second ltr" dir="ltr">every</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَىْءٍ</span><span class="en second ltr" dir="ltr">thing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَهِيدٌ</span><span class="en second ltr" dir="ltr">(is) a Witness.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">those who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَتَنُواْ</span><span class="en second ltr" dir="ltr">persecuted</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُؤْمِنِينَ</span><span class="en second ltr" dir="ltr">the believing men</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْمُؤْمِنَـٰتِ</span><span class="en second ltr" dir="ltr">and the believing women,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَمْ</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتُوبُواْ</span><span class="en second ltr" dir="ltr">they repented,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَهُمْ</span><span class="en second ltr" dir="ltr">then for them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَذَابُ</span><span class="en second ltr" dir="ltr">(is) the punishment</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَهَنَّمَ</span><span class="en second ltr" dir="ltr">(of) Hell</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَهُمْ</span><span class="en second ltr" dir="ltr">and for them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَذَابُ</span><span class="en second ltr" dir="ltr">(is the) punishment</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحَرِيقِ</span><span class="en second ltr" dir="ltr">(of) the Burning Fire.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">those who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ءَامَنُواْ</span><span class="en second ltr" dir="ltr">believe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَعَمِلُواْ</span><span class="en second ltr" dir="ltr">and do</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصَّـٰلِحَـٰتِ</span><span class="en second ltr" dir="ltr">the righteous deeds,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُمْ</span><span class="en second ltr" dir="ltr">for them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَنَّـٰتٌ</span><span class="en second ltr" dir="ltr">(will be) Gardens</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَجْرِى</span><span class="en second ltr" dir="ltr">flow</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَحْتِهَا</span><span class="en second ltr" dir="ltr">underneath it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَنْهَـٰرُ‌ۚ</span><span class="en second ltr" dir="ltr">the rivers.</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَٲلِكَ</span><span class="en second ltr" dir="ltr">That</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَوْزُ</span><span class="en second ltr" dir="ltr">(is) the success</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكَبِيرُ</span><span class="en second ltr" dir="ltr">the great.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَطْشَ</span><span class="en second ltr" dir="ltr">(the) Grip</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">(of) your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَشَدِيدٌ</span><span class="en second ltr" dir="ltr">(is) surely strong.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهُۥ</span><span class="en second ltr" dir="ltr">Indeed He,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُوَ</span><span class="en second ltr" dir="ltr">He</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُبْدِئُ</span><span class="en second ltr" dir="ltr">originates</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيُعِيدُ</span><span class="en second ltr" dir="ltr">and repeats,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَهُوَ</span><span class="en second ltr" dir="ltr">And He</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْغَفُورُ</span><span class="en second ltr" dir="ltr">(is) the Oft-Forgiving,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْوَدُودُ</span><span class="en second ltr" dir="ltr">the Most Loving,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذُو ٱلْعَرْشِ</span><span class="en second ltr" dir="ltr">Owner (of) the Throne</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَجِيدُ</span><span class="en second ltr" dir="ltr">the Glorious,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَعَّالٌ</span><span class="en second ltr" dir="ltr">Doer</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّمَا</span><span class="en second ltr" dir="ltr">of what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُرِيدُ</span><span class="en second ltr" dir="ltr">He intends.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَلْ</span><span class="en second ltr" dir="ltr">Has</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَتَـٰكَ</span><span class="en second ltr" dir="ltr">come to you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَدِيثُ</span><span class="en second ltr" dir="ltr">(the) story</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجُنُودِ</span><span class="en second ltr" dir="ltr">(of) the hosts,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِرْعَوْنَ</span><span class="en second ltr" dir="ltr">Firaun</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَثَمُودَ</span><span class="en second ltr" dir="ltr">and Thamud?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلِ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">Those who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَفَرُواْ</span><span class="en second ltr" dir="ltr">disbelieve</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(are) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَكْذِيبٍ</span><span class="en second ltr" dir="ltr">denial.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱللَّهُ</span><span class="en second ltr" dir="ltr">But Allah</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَرَآئِهِم</span><span class="en second ltr" dir="ltr">behind them,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّحِيطُۢ</span><span class="en second ltr" dir="ltr">encompasses.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلْ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُوَ</span><span class="en second ltr" dir="ltr">It</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُرْءَانٌ</span><span class="en second ltr" dir="ltr">(is) a Quran</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّجِيدٌ</span><span class="en second ltr" dir="ltr">Glorious,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 85-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">In</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَوْحٍ</span><span class="en second ltr" dir="ltr">a Tablet,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّحْفُوظِۭ</span><span class="en second ltr" dir="ltr">Guarded.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

