<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<h1>Word-for-Word Arabic-English Translation of the Quran</h1>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/page-options.php';?>
				<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/vocabulary.php';?>
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Adiyat</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 100-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْعَـٰدِيَـٰتِ</span><span class="en second ltr" dir="ltr">By the racers</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ضَبْحًا</span><span class="en second ltr" dir="ltr">panting,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱلْمُورِيَـٰتِ</span><span class="en second ltr" dir="ltr">And the producers of sparks,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدْحًا</span><span class="en second ltr" dir="ltr">striking</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَٱلْمُغِيرَٲتِ</span><span class="en second ltr" dir="ltr">And the chargers</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صُبْحًا</span><span class="en second ltr" dir="ltr">(at) dawn,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَثَرْنَ</span><span class="en second ltr" dir="ltr">Then raise</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهِۦ</span><span class="en second ltr" dir="ltr">thereby</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَقْعًا</span><span class="en second ltr" dir="ltr">dust,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَوَسَطْنَ بِهِۦ</span><span class="en second ltr" dir="ltr">Then penetrate thereby (in the) center</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَمْعًا</span><span class="en second ltr" dir="ltr">(of) troops,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنَ</span><span class="en second ltr" dir="ltr">mankind,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِرَبِّهِۦ</span><span class="en second ltr" dir="ltr">to his Lord,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَكَنُودٌ</span><span class="en second ltr" dir="ltr">(is) surely ungrateful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِنَّهُۥ</span><span class="en second ltr" dir="ltr">And indeed, he</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَٲلِكَ</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَشَهِيدٌ</span><span class="en second ltr" dir="ltr">surely (is) a witness,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِنَّهُۥ</span><span class="en second ltr" dir="ltr">And indeed he (is),</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِحُبِّ</span><span class="en second ltr" dir="ltr">in (the) love</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْخَيْرِ</span><span class="en second ltr" dir="ltr">(of) wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَشَدِيدٌ</span><span class="en second ltr" dir="ltr">(is) surely intense.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">۞ أَفَلَا</span><span class="en second ltr" dir="ltr">But does not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْلَمُ</span><span class="en second ltr" dir="ltr">he know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بُعْثِرَ</span><span class="en second ltr" dir="ltr">will be scattered</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(is) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقُبُورِ</span><span class="en second ltr" dir="ltr">the graves,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَحُصِّلَ</span><span class="en second ltr" dir="ltr">And is made apparent</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(is) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصُّدُورِ</span><span class="en second ltr" dir="ltr">the breasts?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 100-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبَّهُم</span><span class="en second ltr" dir="ltr">their Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهِمْ</span><span class="en second ltr" dir="ltr">about them,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّخَبِيرُۢ</span><span class="en second ltr" dir="ltr">(is) surely All-Aware.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

