<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Ala</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 87-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَبِّحِ</span><span class="en second ltr" dir="ltr">Glorify</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱسْمَ</span><span class="en second ltr" dir="ltr">(the) name</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">(of) your Lord,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَعْلَى</span><span class="en second ltr" dir="ltr">the Most High,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The One Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَ</span><span class="en second ltr" dir="ltr">created,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَوَّىٰ</span><span class="en second ltr" dir="ltr">then proportioned,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّذِى</span><span class="en second ltr" dir="ltr">And the One Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدَّرَ</span><span class="en second ltr" dir="ltr">measured</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَهَدَىٰ</span><span class="en second ltr" dir="ltr">then guided,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّذِىٓ</span><span class="en second ltr" dir="ltr">And the One Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَخْرَجَ</span><span class="en second ltr" dir="ltr">brings forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَرْعَىٰ</span><span class="en second ltr" dir="ltr">the pasture,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَجَعَلَهُۥ</span><span class="en second ltr" dir="ltr">And then made it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">غُثَآءً</span><span class="en second ltr" dir="ltr">stubble,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحْوَىٰ</span><span class="en second ltr" dir="ltr">dark.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَنُقْرِئُكَ</span><span class="en second ltr" dir="ltr">We will make you recite</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَا</span><span class="en second ltr" dir="ltr">so not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَنسَىٰٓ</span><span class="en second ltr" dir="ltr">you will forget,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">Except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَآءَ ٱللَّهُ‌ۚ</span><span class="en second ltr" dir="ltr">Allah wills</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهُۥ</span><span class="en second ltr" dir="ltr">Indeed, He</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْلَمُ</span><span class="en second ltr" dir="ltr">knows</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجَهْرَ</span><span class="en second ltr" dir="ltr">the manifest</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَخْفَىٰ</span><span class="en second ltr" dir="ltr">is hidden.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَنُيَسِّرُكَ</span><span class="en second ltr" dir="ltr">And We will ease you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِلْيُسْرَىٰ</span><span class="en second ltr" dir="ltr">to the ease.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَذَكِّرْ</span><span class="en second ltr" dir="ltr">So remind,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِن</span><span class="en second ltr" dir="ltr">if</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَّفَعَتِ</span><span class="en second ltr" dir="ltr">benefits</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلذِّكْرَىٰ</span><span class="en second ltr" dir="ltr">the reminder.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَيَذَّكَّرُ</span><span class="en second ltr" dir="ltr">He will pay heed -</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">(one) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَخْشَىٰ</span><span class="en second ltr" dir="ltr">fears (Allah).</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيَتَجَنَّبُهَا</span><span class="en second ltr" dir="ltr">And will avoid it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَشْقَى</span><span class="en second ltr" dir="ltr">the wretched one.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The one who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَصْلَى</span><span class="en second ltr" dir="ltr">will burn</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنَّارَ</span><span class="en second ltr" dir="ltr">(in) the Fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكُبْرَىٰ</span><span class="en second ltr" dir="ltr">[the] great.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَمُوتُ</span><span class="en second ltr" dir="ltr">he will die</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَا</span><span class="en second ltr" dir="ltr">and not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَحْيَىٰ</span><span class="en second ltr" dir="ltr">will live.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدْ</span><span class="en second ltr" dir="ltr">Certainly,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَفْلَحَ</span><span class="en second ltr" dir="ltr">has succeeded</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">(one) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَزَكَّىٰ</span><span class="en second ltr" dir="ltr">purifies (himself),</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَذَكَرَ</span><span class="en second ltr" dir="ltr">And remembers</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱسْمَ</span><span class="en second ltr" dir="ltr">(the) name</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّهِۦ</span><span class="en second ltr" dir="ltr">(of) his Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَصَلَّىٰ</span><span class="en second ltr" dir="ltr">and prays.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلْ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُؤْثِرُونَ</span><span class="en second ltr" dir="ltr">You prefer</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحَيَوٲةَ</span><span class="en second ltr" dir="ltr">the life</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلدُّنْيَا</span><span class="en second ltr" dir="ltr">(of) the world,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأَخِرَةُ</span><span class="en second ltr" dir="ltr">While the Hereafter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَيْرٌ</span><span class="en second ltr" dir="ltr">(is) better</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَبْقَىٰٓ</span><span class="en second ltr" dir="ltr">and ever lasting.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هَـٰذَا</span><span class="en second ltr" dir="ltr">this</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَفِى</span><span class="en second ltr" dir="ltr">surely (is) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصُّحُفِ</span><span class="en second ltr" dir="ltr">the Scriptures</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأُولَىٰ</span><span class="en second ltr" dir="ltr">[the] former,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 87-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صُحُفِ</span><span class="en second ltr" dir="ltr">(The) Scriptures</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِبْرَٲهِيمَ</span><span class="en second ltr" dir="ltr">(of) Ibrahim</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمُوسَىٰ</span><span class="en second ltr" dir="ltr">and Musa.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

