<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Abasa</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 80-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَبَسَ</span><span class="en second ltr" dir="ltr">He frowned</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَلَّىٰٓ</span><span class="en second ltr" dir="ltr">and turned away,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">Because</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَآءَهُ</span><span class="en second ltr" dir="ltr">came to him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَعْمَىٰ</span><span class="en second ltr" dir="ltr">the blind man.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">But what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُدْرِيكَ</span><span class="en second ltr" dir="ltr">would make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَعَلَّهُۥ</span><span class="en second ltr" dir="ltr">that he might</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَزَّكَّىٰٓ</span><span class="en second ltr" dir="ltr">purify himself,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْ</span><span class="en second ltr" dir="ltr">Or</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَذَّكَّرُ</span><span class="en second ltr" dir="ltr">be reminded</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَتَنفَعَهُ</span><span class="en second ltr" dir="ltr">so would benefit him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلذِّكْرَىٰٓ</span><span class="en second ltr" dir="ltr">the reminder?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمَّا</span><span class="en second ltr" dir="ltr">As for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَنِ</span><span class="en second ltr" dir="ltr">(him) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱسْتَغْنَىٰ</span><span class="en second ltr" dir="ltr">considers himself free from need,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَنتَ</span><span class="en second ltr" dir="ltr">So you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهُۥ</span><span class="en second ltr" dir="ltr">to him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَصَدَّىٰ</span><span class="en second ltr" dir="ltr">give attention.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْكَ</span><span class="en second ltr" dir="ltr">upon you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَّا</span><span class="en second ltr" dir="ltr">that not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَزَّكَّىٰ</span><span class="en second ltr" dir="ltr">he purifies himself.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّا</span><span class="en second ltr" dir="ltr">But as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَن</span><span class="en second ltr" dir="ltr">(he) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَآءَكَ</span><span class="en second ltr" dir="ltr">came to you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَسْعَىٰ</span><span class="en second ltr" dir="ltr">striving,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَهُوَ</span><span class="en second ltr" dir="ltr">While he</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَخْشَىٰ</span><span class="en second ltr" dir="ltr">fears,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَنتَ</span><span class="en second ltr" dir="ltr">But you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَنْهُ</span><span class="en second ltr" dir="ltr">from him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَلَهَّىٰ</span><span class="en second ltr" dir="ltr">(are) distracted.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّآ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهَا</span><span class="en second ltr" dir="ltr">Indeed, it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَذْكِرَةٌ</span><span class="en second ltr" dir="ltr">(is) a reminder,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَمَن</span><span class="en second ltr" dir="ltr">So whosoever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَآءَ</span><span class="en second ltr" dir="ltr">wills</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَكَرَهُۥ</span><span class="en second ltr" dir="ltr">may remember it.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">In</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صُحُفٍ</span><span class="en second ltr" dir="ltr">sheets</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّكَرَّمَةٍ</span><span class="en second ltr" dir="ltr">honored,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّرْفُوعَةٍ</span><span class="en second ltr" dir="ltr">Exalted,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّطَهَّرَةِۭ</span><span class="en second ltr" dir="ltr">purified,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِأَيْدِى</span><span class="en second ltr" dir="ltr">In (the) hands</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَفَرَةٍ</span><span class="en second ltr" dir="ltr">(of) scribes.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كِرَامِۭ</span><span class="en second ltr" dir="ltr">Noble,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَرَرَةٍ</span><span class="en second ltr" dir="ltr">dutiful.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُتِلَ</span><span class="en second ltr" dir="ltr">Is destroyed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">the man,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَآ</span><span class="en second ltr" dir="ltr">how</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَكْفَرَهُۥ</span><span class="en second ltr" dir="ltr">ungrateful is he!</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْ</span><span class="en second ltr" dir="ltr">From</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَىِّ</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَىْءٍ</span><span class="en second ltr" dir="ltr">thing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَهُۥ</span><span class="en second ltr" dir="ltr">He created him?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">From</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُّطْفَةٍ</span><span class="en second ltr" dir="ltr">a sperm drop</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَهُۥ</span><span class="en second ltr" dir="ltr">He created him,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَقَدَّرَهُۥ</span><span class="en second ltr" dir="ltr">then He proportioned him,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّبِيلَ</span><span class="en second ltr" dir="ltr">the way,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَسَّرَهُۥ</span><span class="en second ltr" dir="ltr">He made easy for him,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمَاتَهُۥ</span><span class="en second ltr" dir="ltr">He causes him to die</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَقْبَرَهُۥ</span><span class="en second ltr" dir="ltr">and provides a grave for him,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-22" id="22" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَآءَ</span><span class="en second ltr" dir="ltr">He wills,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنشَرَهُۥ</span><span class="en second ltr" dir="ltr">He will resurrect him.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-23" id="23" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَمَّا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَقْضِ</span><span class="en second ltr" dir="ltr">he has accomplished</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَآ</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمَرَهُۥ</span><span class="en second ltr" dir="ltr">He commanded him.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-24" id="24" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلْيَنظُرِ</span><span class="en second ltr" dir="ltr">Then let look</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">the man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">at</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">طَعَامِهِۦٓ</span><span class="en second ltr" dir="ltr">his food,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-25" id="25" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنَّا</span><span class="en second ltr" dir="ltr">We</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَبَبْنَا</span><span class="en second ltr" dir="ltr">[We] poured down</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَآءَ</span><span class="en second ltr" dir="ltr">the water</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَبًّا</span><span class="en second ltr" dir="ltr">(in) abundance,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-26" id="26" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَقَقْنَا</span><span class="en second ltr" dir="ltr">We cleaved</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضَ</span><span class="en second ltr" dir="ltr">the earth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَقًّا</span><span class="en second ltr" dir="ltr">splitting,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-27" id="27" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَنۢبَتْنَا</span><span class="en second ltr" dir="ltr">Then We caused to grow</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِيهَا</span><span class="en second ltr" dir="ltr">therein</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حَبًّا</span><span class="en second ltr" dir="ltr">grain,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>27<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-28" id="28" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَعِنَبًا</span><span class="en second ltr" dir="ltr">And grapes</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَقَضْبًا</span><span class="en second ltr" dir="ltr">and green vegetables,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>28<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-29" id="29" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَزَيْتُونًا</span><span class="en second ltr" dir="ltr">And olive</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَنَخْلاً</span><span class="en second ltr" dir="ltr">and date-palms,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>29<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-30" id="30" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَحَدَآئِقَ</span><span class="en second ltr" dir="ltr">And gardens</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">غُلْبًا</span><span class="en second ltr" dir="ltr">(of) thick foliage,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>30<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-31" id="31" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَفَـٰكِهَةً</span><span class="en second ltr" dir="ltr">And fruits</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَبًّا</span><span class="en second ltr" dir="ltr">and grass,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>31<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-32" id="32" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّتَـٰعًا</span><span class="en second ltr" dir="ltr">(As) a provision</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّكُمْ</span><span class="en second ltr" dir="ltr">for you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلِأَنْعَـٰمِكُمْ</span><span class="en second ltr" dir="ltr">and for your cattle.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>32<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-33" id="33" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَإِذَا</span><span class="en second ltr" dir="ltr">But when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَآءَتِ</span><span class="en second ltr" dir="ltr">comes</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصَّآخَّةُ</span><span class="en second ltr" dir="ltr">the Deafening Blast,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>33<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-34" id="34" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَ</span><span class="en second ltr" dir="ltr">(The) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَفِرُّ</span><span class="en second ltr" dir="ltr">will flee</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَرْءُ</span><span class="en second ltr" dir="ltr">a man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْ</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَخِيهِ</span><span class="en second ltr" dir="ltr">his brother,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>34<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-35" id="35" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأُمِّهِۦ</span><span class="en second ltr" dir="ltr">And his mother</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَبِيهِ</span><span class="en second ltr" dir="ltr">and his father,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>35<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-36" id="36" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَصَـٰحِبَتِهِۦ</span><span class="en second ltr" dir="ltr">And his wife</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَبَنِيهِ</span><span class="en second ltr" dir="ltr">and his children,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>36<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-37" id="37" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِكُلِّ</span><span class="en second ltr" dir="ltr">For every</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱمْرِىٍٕ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِّنْهُمْ</span><span class="en second ltr" dir="ltr">among them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَأْنٌ</span><span class="en second ltr" dir="ltr">(will be) a matter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُغْنِيهِ</span><span class="en second ltr" dir="ltr">occupying him.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>37<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-38" id="38" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وُجُوهٌ</span><span class="en second ltr" dir="ltr">Faces,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّسْفِرَةٌ</span><span class="en second ltr" dir="ltr">(will be) bright,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>38<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-39" id="39" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ضَاحِكَةٌ</span><span class="en second ltr" dir="ltr">Laughing,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّسْتَبْشِرَةٌ</span><span class="en second ltr" dir="ltr">rejoicing at good news.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>39<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-40" id="40" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَوُجُوهٌ</span><span class="en second ltr" dir="ltr">And faces,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهَا</span><span class="en second ltr" dir="ltr">upon them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">غَبَرَةٌ</span><span class="en second ltr" dir="ltr">(will be) dust,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>40<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-41" id="41" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَرْهَقُهَا</span><span class="en second ltr" dir="ltr">Will cover them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَتَرَةٌ</span><span class="en second ltr" dir="ltr">darkness.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>41<span class="icon rightBracket"> </span></span></p>
<p class="ayah 80-42" id="42" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُوْلَـٰٓئِكَ</span><span class="en second ltr" dir="ltr">Those</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُمُ</span><span class="en second ltr" dir="ltr">[they]</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكَفَرَةُ</span><span class="en second ltr" dir="ltr">(are) the disbelievers,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفَجَرَةُ</span><span class="en second ltr" dir="ltr">the wicked ones.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>42<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

