<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Alaq</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 96-1" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱقْرَأْ</span><span class="en second ltr" dir="ltr">Read</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱسْمِ</span><span class="en second ltr" dir="ltr">in (the) name</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">(of) your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">the One Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَ</span><span class="en second ltr" dir="ltr">created -</span></span></span> <a href="#!/quran-wordbyword/96:1" class="ayahNumber" data-verse="6107"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-2" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَ</span><span class="en second ltr" dir="ltr">He created</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنَ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنْ</span><span class="en second ltr" dir="ltr">from</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَقٍ</span><span class="en second ltr" dir="ltr">a clinging substance.</span></span></span> <a href="#!/quran-wordbyword/96:2" class="ayahNumber" data-verse="6108"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-3" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱقْرَأْ</span><span class="en second ltr" dir="ltr">Read,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَرَبُّكَ</span><span class="en second ltr" dir="ltr">and your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَكْرَمُ</span><span class="en second ltr" dir="ltr">(is) the Most Generous,</span></span></span> <a href="#!/quran-wordbyword/96:3" class="ayahNumber" data-verse="6109"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-4" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The One Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَّمَ</span><span class="en second ltr" dir="ltr">taught</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْقَلَمِ</span><span class="en second ltr" dir="ltr">by the pen,</span></span></span> <a href="#!/quran-wordbyword/96:4" class="ayahNumber" data-verse="6110"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-5" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَّمَ</span><span class="en second ltr" dir="ltr">Taught</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنَ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَمْ</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْلَمْ</span><span class="en second ltr" dir="ltr">he knew.</span></span></span> <a href="#!/quran-wordbyword/96:5" class="ayahNumber" data-verse="6111"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-6" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّآ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنَ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَيَطْغَىٰٓ</span><span class="en second ltr" dir="ltr">surely transgresses,</span></span></span> <a href="#!/quran-wordbyword/96:6" class="ayahNumber" data-verse="6112"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-7" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">Because</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَّءَاهُ</span><span class="en second ltr" dir="ltr">he sees himself</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱسْتَغْنَىٰٓ</span><span class="en second ltr" dir="ltr">self-sufficient.</span></span></span> <a href="#!/quran-wordbyword/96:7" class="ayahNumber" data-verse="6113"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-8" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَىٰ</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلرُّجْعَىٰٓ</span><span class="en second ltr" dir="ltr">(is) the return.</span></span></span> <a href="#!/quran-wordbyword/96:8" class="ayahNumber" data-verse="6114"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-9" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَرَءَيْتَ</span><span class="en second ltr" dir="ltr">Have you seen</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">the one who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَنْهَىٰ</span><span class="en second ltr" dir="ltr">forbids</span></span></span> <a href="#!/quran-wordbyword/96:9" class="ayahNumber" data-verse="6115"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-10" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَبْدًا</span><span class="en second ltr" dir="ltr">A slave</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَلَّىٰٓ</span><span class="en second ltr" dir="ltr">he prays?</span></span></span> <a href="#!/quran-wordbyword/96:10" class="ayahNumber" data-verse="6116"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-11" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَرَءَيْتَ</span><span class="en second ltr" dir="ltr">Have you seen</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِن</span><span class="en second ltr" dir="ltr">if</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَانَ</span><span class="en second ltr" dir="ltr">he is</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَى</span><span class="en second ltr" dir="ltr">upon</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْهُدَىٰٓ</span><span class="en second ltr" dir="ltr">[the] guidance,</span></span></span> <a href="#!/quran-wordbyword/96:11" class="ayahNumber" data-verse="6117"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-12" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْ</span><span class="en second ltr" dir="ltr">Or</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمَرَ</span><span class="en second ltr" dir="ltr">he enjoins</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلتَّقْوَىٰٓ</span><span class="en second ltr" dir="ltr">[of the] righteousness?</span></span></span> <a href="#!/quran-wordbyword/96:12" class="ayahNumber" data-verse="6118"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-13" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَرَءَيْتَ</span><span class="en second ltr" dir="ltr">Have you seen</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِن</span><span class="en second ltr" dir="ltr">if</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَّبَ</span><span class="en second ltr" dir="ltr">he denies</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَلَّىٰٓ</span><span class="en second ltr" dir="ltr">and turns away?</span></span></span> <a href="#!/quran-wordbyword/96:13" class="ayahNumber" data-verse="6119"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-14" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Does not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْلَم</span><span class="en second ltr" dir="ltr">he know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِأَنَّ</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهَ</span><span class="en second ltr" dir="ltr">Allah</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرَىٰ</span><span class="en second ltr" dir="ltr">sees?</span></span></span> <a href="#!/quran-wordbyword/96:14" class="ayahNumber" data-verse="6120"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-15" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَئِن</span><span class="en second ltr" dir="ltr">If</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّمْ</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَنتَهِ</span><span class="en second ltr" dir="ltr">he desists,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَنَسْفَعَۢا</span><span class="en second ltr" dir="ltr">surely We will drag him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلنَّاصِيَةِ</span><span class="en second ltr" dir="ltr">by the forelock,</span></span></span> <a href="#!/quran-wordbyword/96:15" class="ayahNumber" data-verse="6121"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-16" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَاصِيَةٍ</span><span class="en second ltr" dir="ltr">A forelock</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَـٰذِبَةٍ</span><span class="en second ltr" dir="ltr">lying,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَاطِئَةٍ</span><span class="en second ltr" dir="ltr">sinful.</span></span></span> <a href="#!/quran-wordbyword/96:16" class="ayahNumber" data-verse="6122"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-17" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلْيَدْعُ</span><span class="en second ltr" dir="ltr">Then let him call</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَادِيَهُۥ</span><span class="en second ltr" dir="ltr">his associates,</span></span></span> <a href="#!/quran-wordbyword/96:17" class="ayahNumber" data-verse="6123"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-18" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَنَدْعُ</span><span class="en second ltr" dir="ltr">We will call</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلزَّبَانِيَةَ</span><span class="en second ltr" dir="ltr">the Angels of Hell.</span></span></span> <a href="#!/quran-wordbyword/96:18" class="ayahNumber" data-verse="6124"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></a></p>
<p class="ayah 96-19" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">(Do) not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُطِعْهُ</span><span class="en second ltr" dir="ltr">obey him.</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱسْجُدْ</span><span class="en second ltr" dir="ltr">But prostrate</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱقْتَرِب ۩</span><span class="en second ltr" dir="ltr">and draw near (to Allah).</span></span></span> <a href="#!/quran-wordbyword/96:19" class="ayahNumber" data-verse="6125"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></a></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

