<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Balad</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 90-1" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَآ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُقْسِمُ</span><span class="en second ltr" dir="ltr">I swear</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهَـٰذَا</span><span class="en second ltr" dir="ltr">by this</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبَلَدِ</span><span class="en second ltr" dir="ltr">city,</span></span></span> <a href="#!/quran-wordbyword/90:1" class="ayahNumber" data-verse="6024"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-2" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَنتَ</span><span class="en second ltr" dir="ltr">And you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حِلُّۢ</span><span class="en second ltr" dir="ltr">(are) free (to dwell)</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِهَـٰذَا</span><span class="en second ltr" dir="ltr">in this</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبَلَدِ</span><span class="en second ltr" dir="ltr">city.</span></span></span> <a href="#!/quran-wordbyword/90:2" class="ayahNumber" data-verse="6025"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-3" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَوَالِدٍ</span><span class="en second ltr" dir="ltr">And the begetter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">and what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَدَ</span><span class="en second ltr" dir="ltr">he begot.</span></span></span> <a href="#!/quran-wordbyword/90:3" class="ayahNumber" data-verse="6026"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-4" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَقَدْ</span><span class="en second ltr" dir="ltr">Certainly,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقْنَا</span><span class="en second ltr" dir="ltr">We have created</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنَ</span><span class="en second ltr" dir="ltr">man</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">(to be) in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَبَدٍ</span><span class="en second ltr" dir="ltr">hardship.</span></span></span> <a href="#!/quran-wordbyword/90:4" class="ayahNumber" data-verse="6027"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-5" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيَحْسَبُ</span><span class="en second ltr" dir="ltr">Does he think</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّن</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَقْدِرَ</span><span class="en second ltr" dir="ltr">has power</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِ</span><span class="en second ltr" dir="ltr">over him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحَدٌ</span><span class="en second ltr" dir="ltr">anyone?</span></span></span> <a href="#!/quran-wordbyword/90:5" class="ayahNumber" data-verse="6028"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-6" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَقُولُ</span><span class="en second ltr" dir="ltr">He will say,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَهْلَكْتُ</span><span class="en second ltr" dir="ltr">`I have squandered</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَالاً</span><span class="en second ltr" dir="ltr">wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لُّبَدًا</span><span class="en second ltr" dir="ltr">abundant.`</span></span></span> <a href="#!/quran-wordbyword/90:6" class="ayahNumber" data-verse="6029"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-7" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَيَحْسَبُ</span><span class="en second ltr" dir="ltr">Does he think</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّمْ</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرَهُۥٓ</span><span class="en second ltr" dir="ltr">sees him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحَدٌ</span><span class="en second ltr" dir="ltr">anyone?</span></span></span> <a href="#!/quran-wordbyword/90:7" class="ayahNumber" data-verse="6030"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-8" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَلَمْ</span><span class="en second ltr" dir="ltr">Have not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَجْعَل</span><span class="en second ltr" dir="ltr">We made</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَّهُۥ</span><span class="en second ltr" dir="ltr">for him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَيْنَيْنِ</span><span class="en second ltr" dir="ltr">two eyes?</span></span></span> <a href="#!/quran-wordbyword/90:8" class="ayahNumber" data-verse="6031"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-9" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلِسَانًا</span><span class="en second ltr" dir="ltr">And a tongue,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَشَفَتَيْنِ</span><span class="en second ltr" dir="ltr">and two lips?</span></span></span> <a href="#!/quran-wordbyword/90:9" class="ayahNumber" data-verse="6032"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-10" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَهَدَيْنَـٰهُ</span><span class="en second ltr" dir="ltr">And shown him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنَّجْدَيْنِ</span><span class="en second ltr" dir="ltr">the two ways?</span></span></span> <a href="#!/quran-wordbyword/90:10" class="ayahNumber" data-verse="6033"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-11" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَا</span><span class="en second ltr" dir="ltr">But not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱقْتَحَمَ</span><span class="en second ltr" dir="ltr">he has attempted</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَقَبَةَ</span><span class="en second ltr" dir="ltr">the steep path.</span></span></span> <a href="#!/quran-wordbyword/90:11" class="ayahNumber" data-verse="6034"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-12" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">can make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَقَبَةُ</span><span class="en second ltr" dir="ltr">the steep path is?</span></span></span> <a href="#!/quran-wordbyword/90:12" class="ayahNumber" data-verse="6035"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-13" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَكُّ</span><span class="en second ltr" dir="ltr">(It is) freeing</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَقَبَةٍ</span><span class="en second ltr" dir="ltr">a neck,</span></span></span> <a href="#!/quran-wordbyword/90:13" class="ayahNumber" data-verse="6036"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-14" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْ</span><span class="en second ltr" dir="ltr">Or</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِطْعَـٰمٌ</span><span class="en second ltr" dir="ltr">feeding</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمٍ</span><span class="en second ltr" dir="ltr">a day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِى مَسْغَبَةٍ</span><span class="en second ltr" dir="ltr">of severe hunger.</span></span></span> <a href="#!/quran-wordbyword/90:14" class="ayahNumber" data-verse="6037"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-15" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتِيمًا</span><span class="en second ltr" dir="ltr">An orphan</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَا مَقْرَبَةٍ</span><span class="en second ltr" dir="ltr">of near relationship,</span></span></span> <a href="#!/quran-wordbyword/90:15" class="ayahNumber" data-verse="6038"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-16" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْ</span><span class="en second ltr" dir="ltr">Or</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِسْكِينًا</span><span class="en second ltr" dir="ltr">a needy person</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَا مَتْرَبَةٍ</span><span class="en second ltr" dir="ltr">in misery,</span></span></span> <a href="#!/quran-wordbyword/90:16" class="ayahNumber" data-verse="6039"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-17" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَانَ</span><span class="en second ltr" dir="ltr">he is</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنَ</span><span class="en second ltr" dir="ltr">of</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِينَ</span><span class="en second ltr" dir="ltr">those who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ءَامَنُواْ</span><span class="en second ltr" dir="ltr">believe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَاصَوْاْ</span><span class="en second ltr" dir="ltr">and enjoin each other</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلصَّبْرِ</span><span class="en second ltr" dir="ltr">to patience,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَاصَوْاْ</span><span class="en second ltr" dir="ltr">and enjoin each other</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْمَرْحَمَةِ</span><span class="en second ltr" dir="ltr">to compassion.</span></span></span> <a href="#!/quran-wordbyword/90:17" class="ayahNumber" data-verse="6040"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-18" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُوْلَـٰٓئِكَ</span><span class="en second ltr" dir="ltr">Those</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَصْحَـٰبُ</span><span class="en second ltr" dir="ltr">(are the) companions</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَيْمَنَةِ</span><span class="en second ltr" dir="ltr">(of) the right hand.</span></span></span> <a href="#!/quran-wordbyword/90:18" class="ayahNumber" data-verse="6041"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-19" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّذِينَ</span><span class="en second ltr" dir="ltr">But those who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَفَرُواْ</span><span class="en second ltr" dir="ltr">disbelieve</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِـَٔـايَـٰتِنَا</span><span class="en second ltr" dir="ltr">in Our Verses,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُمْ</span><span class="en second ltr" dir="ltr">they</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَصْحَـٰبُ</span><span class="en second ltr" dir="ltr">(are the) companions</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَشْــَٔمَةِ</span><span class="en second ltr" dir="ltr">(of) the left hand.</span></span></span> <a href="#!/quran-wordbyword/90:19" class="ayahNumber" data-verse="6042"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></a></p>
<p class="ayah 90-20" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِمْ</span><span class="en second ltr" dir="ltr">Over them,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَارٌ</span><span class="en second ltr" dir="ltr">(will be the) Fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّؤْصَدَةُۢ</span><span class="en second ltr" dir="ltr">closed in.</span></span></span> <a href="#!/quran-wordbyword/90:20" class="ayahNumber" data-verse="6043"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></a></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

