<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Humazah</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 104-1" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَيْلٌ</span><span class="en second ltr" dir="ltr">Woe</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّكُلِّ</span><span class="en second ltr" dir="ltr">to every</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُمَزَةٍ</span><span class="en second ltr" dir="ltr">slanderer</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لُّمَزَةٍ</span><span class="en second ltr" dir="ltr">backbiter!</span></span></span> <a href="#!/quran-wordbyword/104:1" class="ayahNumber" data-verse="6180"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-2" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The one who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَمَعَ</span><span class="en second ltr" dir="ltr">collects</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَالاً</span><span class="en second ltr" dir="ltr">wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَعَدَّدَهُۥ</span><span class="en second ltr" dir="ltr">and counts it.</span></span></span> <a href="#!/quran-wordbyword/104:2" class="ayahNumber" data-verse="6181"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-3" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَحْسَبُ</span><span class="en second ltr" dir="ltr">Thinking</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَنَّ</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَالَهُۥٓ</span><span class="en second ltr" dir="ltr">his wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَخْلَدَهُۥ</span><span class="en second ltr" dir="ltr">will make him immortal</span></span></span> <a href="#!/quran-wordbyword/104:3" class="ayahNumber" data-verse="6182"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-4" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا‌ۖ</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَيُنۢبَذَنَّ</span><span class="en second ltr" dir="ltr">Surely he will be thrown</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحُطَمَةِ</span><span class="en second ltr" dir="ltr">the Crusher.</span></span></span> <a href="#!/quran-wordbyword/104:4" class="ayahNumber" data-verse="6183"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-5" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">will make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْحُطَمَةُ</span><span class="en second ltr" dir="ltr">the Crusher (is)?</span></span></span> <a href="#!/quran-wordbyword/104:5" class="ayahNumber" data-verse="6184"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-6" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَارُ</span><span class="en second ltr" dir="ltr">A Fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱللَّهِ ٱلْمُوقَدَةُ</span><span class="en second ltr" dir="ltr">kindled by Allah,</span></span></span> <a href="#!/quran-wordbyword/104:6" class="ayahNumber" data-verse="6185"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-7" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّتِى</span><span class="en second ltr" dir="ltr">Which</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَطَّلِعُ</span><span class="en second ltr" dir="ltr">mounts up</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَى</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَفْــِٔدَةِ</span><span class="en second ltr" dir="ltr">the hearts.</span></span></span> <a href="#!/quran-wordbyword/104:7" class="ayahNumber" data-verse="6186"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-8" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهَا</span><span class="en second ltr" dir="ltr">Indeed, it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْهِم</span><span class="en second ltr" dir="ltr">(will be) upon them</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّؤْصَدَةٌ</span><span class="en second ltr" dir="ltr">closed over,</span></span></span> <a href="#!/quran-wordbyword/104:8" class="ayahNumber" data-verse="6187"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></a></p>
<p class="ayah 104-9" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِى</span><span class="en second ltr" dir="ltr">In</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَمَدٍ</span><span class="en second ltr" dir="ltr">columns</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّمَدَّدَةِۭ</span><span class="en second ltr" dir="ltr">extended.</span></span></span> <a href="#!/quran-wordbyword/104:9" class="ayahNumber" data-verse="6188"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></a></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

