<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Infitar</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 82-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّمَآءُ</span><span class="en second ltr" dir="ltr">the sky</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنفَطَرَتْ</span><span class="en second ltr" dir="ltr">(is) cleft asunder,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكَوَاكِبُ</span><span class="en second ltr" dir="ltr">the stars</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنتَثَرَتْ</span><span class="en second ltr" dir="ltr">scatter,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبِحَارُ</span><span class="en second ltr" dir="ltr">the seas</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فُجِّرَتْ</span><span class="en second ltr" dir="ltr">are made to gush forth,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْقُبُورُ</span><span class="en second ltr" dir="ltr">the graves</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بُعْثِرَتْ</span><span class="en second ltr" dir="ltr">are overturned,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلِمَتْ</span><span class="en second ltr" dir="ltr">Will know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَفْسٌ</span><span class="en second ltr" dir="ltr">a soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قَدَّمَتْ</span><span class="en second ltr" dir="ltr">it has sent forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَخَّرَتْ</span><span class="en second ltr" dir="ltr">and left behind.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَـٰٓأَيُّهَا</span><span class="en second ltr" dir="ltr">O</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">man!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">What</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">غَرَّكَ</span><span class="en second ltr" dir="ltr">has deceived you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِرَبِّكَ</span><span class="en second ltr" dir="ltr">concerning your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكَرِيمِ</span><span class="en second ltr" dir="ltr">the Most Noble,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">Who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَلَقَكَ</span><span class="en second ltr" dir="ltr">created you,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَوَّٮٰكَ</span><span class="en second ltr" dir="ltr">then fashioned you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَعَدَلَكَ</span><span class="en second ltr" dir="ltr">then balanced you?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فِىٓ</span><span class="en second ltr" dir="ltr">In</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَىِّ</span><span class="en second ltr" dir="ltr">whatever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صُورَةٍ</span><span class="en second ltr" dir="ltr">form</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّا</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَآءَ</span><span class="en second ltr" dir="ltr">He willed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَكَّبَكَ</span><span class="en second ltr" dir="ltr">He assembled you.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَلَّا</span><span class="en second ltr" dir="ltr">Nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَلْ</span><span class="en second ltr" dir="ltr">But</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُكَذِّبُونَ</span><span class="en second ltr" dir="ltr">you deny</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلدِّينِ</span><span class="en second ltr" dir="ltr">the Judgment.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِنَّ</span><span class="en second ltr" dir="ltr">And indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْكُمْ</span><span class="en second ltr" dir="ltr">over you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَحَـٰفِظِينَ</span><span class="en second ltr" dir="ltr">(are) surely guardians,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كِرَامًا</span><span class="en second ltr" dir="ltr">Noble</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَـٰتِبِينَ</span><span class="en second ltr" dir="ltr">recording,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْلَمُونَ</span><span class="en second ltr" dir="ltr">They know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">whatever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَفْعَلُونَ</span><span class="en second ltr" dir="ltr">you do.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَبْرَارَ</span><span class="en second ltr" dir="ltr">the righteous</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَفِى</span><span class="en second ltr" dir="ltr">(will be) surely in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَعِيمٍ</span><span class="en second ltr" dir="ltr">bliss,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِنَّ</span><span class="en second ltr" dir="ltr">And indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْفُجَّارَ</span><span class="en second ltr" dir="ltr">the wicked</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَفِى</span><span class="en second ltr" dir="ltr">(will be) surely in</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">جَحِيمٍ</span><span class="en second ltr" dir="ltr">Hellfire.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَصْلَوْنَهَا</span><span class="en second ltr" dir="ltr">They will burn (in) it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَ</span><span class="en second ltr" dir="ltr">(on the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلدِّينِ</span><span class="en second ltr" dir="ltr">(of) the Judgment,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُمْ</span><span class="en second ltr" dir="ltr">they</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَنْهَا</span><span class="en second ltr" dir="ltr">from it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِغَآئِبِينَ</span><span class="en second ltr" dir="ltr">(will be) absent.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَآ</span><span class="en second ltr" dir="ltr">And what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">can make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلدِّينِ</span><span class="en second ltr" dir="ltr">(of) the Judgment?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثُمَّ</span><span class="en second ltr" dir="ltr">Then,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَآ</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَدْرَٮٰكَ</span><span class="en second ltr" dir="ltr">can make you know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمُ</span><span class="en second ltr" dir="ltr">(is the) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلدِّينِ</span><span class="en second ltr" dir="ltr">(of) the Judgment?</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 82-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَ</span><span class="en second ltr" dir="ltr">(The) Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَمْلِكُ</span><span class="en second ltr" dir="ltr">will have power</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَفْسٌ</span><span class="en second ltr" dir="ltr">a soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّنَفْسٍ</span><span class="en second ltr" dir="ltr">for a soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَيْــًٔا‌ۖ</span><span class="en second ltr" dir="ltr">anything,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأَمْرُ</span><span class="en second ltr" dir="ltr">and the Command</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">that Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلَّهِ</span><span class="en second ltr" dir="ltr">(will be) with Allah.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

