<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Lail</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 92-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّيْلِ</span><span class="en second ltr" dir="ltr">By the night</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَغْشَىٰ</span><span class="en second ltr" dir="ltr">it covers,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلنَّهَارِ</span><span class="en second ltr" dir="ltr">And the day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَجَلَّىٰ</span><span class="en second ltr" dir="ltr">it shines in brightness,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا خَلَقَ</span><span class="en second ltr" dir="ltr">And He Who created</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلذَّكَرَ</span><span class="en second ltr" dir="ltr">the male</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأُنثَىٰٓ</span><span class="en second ltr" dir="ltr">and the female,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سَعْيَكُمْ</span><span class="en second ltr" dir="ltr">your efforts</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَشَتَّىٰ</span><span class="en second ltr" dir="ltr">(are) surely diverse.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَمَّا</span><span class="en second ltr" dir="ltr">Then as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَنْ</span><span class="en second ltr" dir="ltr">(him) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَعْطَىٰ</span><span class="en second ltr" dir="ltr">gives</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱتَّقَىٰ</span><span class="en second ltr" dir="ltr">and fears,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَصَدَّقَ</span><span class="en second ltr" dir="ltr">And believes</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْحُسْنَىٰ</span><span class="en second ltr" dir="ltr">in the best,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَنُيَسِّرُهُۥ</span><span class="en second ltr" dir="ltr">Then We will ease him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِلْيُسْرَىٰ</span><span class="en second ltr" dir="ltr">towards [the] ease.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَمَّا</span><span class="en second ltr" dir="ltr">But as for</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَنۢ</span><span class="en second ltr" dir="ltr">(him) who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بَخِلَ</span><span class="en second ltr" dir="ltr">withholds</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱسْتَغْنَىٰ</span><span class="en second ltr" dir="ltr">and considers himself free from need,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-9" id="9" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَكَذَّبَ</span><span class="en second ltr" dir="ltr">And denies</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْحُسْنَىٰ</span><span class="en second ltr" dir="ltr">the best,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-10" id="10" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَسَنُيَسِّرُهُۥ</span><span class="en second ltr" dir="ltr">Then We will ease him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِلْعُسْرَىٰ</span><span class="en second ltr" dir="ltr">towards [the] difficulty.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-11" id="11" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُغْنِى</span><span class="en second ltr" dir="ltr">will avail</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَنْهُ</span><span class="en second ltr" dir="ltr">him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَالُهُۥٓ</span><span class="en second ltr" dir="ltr">his wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَرَدَّىٰٓ</span><span class="en second ltr" dir="ltr">he falls.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-12" id="12" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّ</span><span class="en second ltr" dir="ltr">Indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَيْنَا</span><span class="en second ltr" dir="ltr">upon Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَلْهُدَىٰ</span><span class="en second ltr" dir="ltr">(is) the guidance.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-13" id="13" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِنَّ</span><span class="en second ltr" dir="ltr">And indeed,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَنَا</span><span class="en second ltr" dir="ltr">for Us</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَلْأَخِرَةَ</span><span class="en second ltr" dir="ltr">(is) the Hereafter</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلْأُولَىٰ</span><span class="en second ltr" dir="ltr">and the first (life).</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-14" id="14" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَنذَرْتُكُمْ</span><span class="en second ltr" dir="ltr">So I warn you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَارًا</span><span class="en second ltr" dir="ltr">(of) a Fire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَلَظَّىٰ</span><span class="en second ltr" dir="ltr">blazing,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-15" id="15" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَا</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَصْلَـٰهَآ</span><span class="en second ltr" dir="ltr">will burn (in) it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَشْقَى</span><span class="en second ltr" dir="ltr">the most wretched,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-16" id="16" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The one who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَذَّبَ</span><span class="en second ltr" dir="ltr">denied</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَتَوَلَّىٰ</span><span class="en second ltr" dir="ltr">and turned away.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-17" id="17" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَسَيُجَنَّبُهَا</span><span class="en second ltr" dir="ltr">But will be removed from it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَتْقَى</span><span class="en second ltr" dir="ltr">the righteous,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-18" id="18" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلَّذِى</span><span class="en second ltr" dir="ltr">The one who</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يُؤْتِى</span><span class="en second ltr" dir="ltr">gives</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَالَهُۥ</span><span class="en second ltr" dir="ltr">his wealth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَتَزَكَّىٰ</span><span class="en second ltr" dir="ltr">purifying himself,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-19" id="19" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِأَحَدٍ</span><span class="en second ltr" dir="ltr">for anyone</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عِندَهُۥ</span><span class="en second ltr" dir="ltr">with him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِن</span><span class="en second ltr" dir="ltr">any</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نِّعْمَةٍ</span><span class="en second ltr" dir="ltr">favor</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُجْزَىٰٓ</span><span class="en second ltr" dir="ltr">to be recompensed</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-20" id="20" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">Except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱبْتِغَآءَ</span><span class="en second ltr" dir="ltr">seeking</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَجْهِ</span><span class="en second ltr" dir="ltr">(the) Countenance</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبِّهِ</span><span class="en second ltr" dir="ltr">(of) his Lord,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَعْلَىٰ</span><span class="en second ltr" dir="ltr">the Most High.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></span></p>
<p class="ayah 92-21" id="21" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَسَوْفَ</span><span class="en second ltr" dir="ltr">And soon, surely</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرْضَىٰ</span><span class="en second ltr" dir="ltr">he will be pleased.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

