<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > Al-Zilzal</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 99-1" id="1" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">زُلْزِلَتِ</span><span class="en second ltr" dir="ltr">is shaken</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضُ</span><span class="en second ltr" dir="ltr">the earth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">زِلْزَالَهَا</span><span class="en second ltr" dir="ltr">with its earthquake,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-2" id="2" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَأَخْرَجَتِ</span><span class="en second ltr" dir="ltr">And brings forth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْأَرْضُ</span><span class="en second ltr" dir="ltr">the earth</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَثْقَالَهَا</span><span class="en second ltr" dir="ltr">its burdens,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-3" id="3" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَقَالَ</span><span class="en second ltr" dir="ltr">And says</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْإِنسَـٰنُ</span><span class="en second ltr" dir="ltr">man,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَا</span><span class="en second ltr" dir="ltr">`What</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهَا</span><span class="en second ltr" dir="ltr">(is) with it?`</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-4" id="4" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">That Day,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تُحَدِّثُ</span><span class="en second ltr" dir="ltr">it will report</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَخْبَارَهَا</span><span class="en second ltr" dir="ltr">its news,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-5" id="5" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِأَنَّ</span><span class="en second ltr" dir="ltr">Because</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبَّكَ</span><span class="en second ltr" dir="ltr">your Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَوْحَىٰ</span><span class="en second ltr" dir="ltr">inspired</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَهَا</span><span class="en second ltr" dir="ltr">[to] it.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-6" id="6" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَوْمَئِذٍ</span><span class="en second ltr" dir="ltr">That Day</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَصْدُرُ</span><span class="en second ltr" dir="ltr">will proceed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنَّاسُ</span><span class="en second ltr" dir="ltr">the mankind</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَشْتَاتًا</span><span class="en second ltr" dir="ltr">(in) scattered groups</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّيُرَوْاْ</span><span class="en second ltr" dir="ltr">to be shown</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَعْمَـٰلَهُمْ</span><span class="en second ltr" dir="ltr">their deeds.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-7" id="7" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَمَن</span><span class="en second ltr" dir="ltr">So whoever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْمَلْ</span><span class="en second ltr" dir="ltr">does</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِثْقَالَ</span><span class="en second ltr" dir="ltr">(equal to the) weight</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَرَّةٍ</span><span class="en second ltr" dir="ltr">(of) an atom</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">خَيْرًا</span><span class="en second ltr" dir="ltr">good,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرَهُۥ</span><span class="en second ltr" dir="ltr">will see it,</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></span></p>
<p class="ayah 99-8" id="8" ><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَن</span><span class="en second ltr" dir="ltr">And whoever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَعْمَلْ</span><span class="en second ltr" dir="ltr">does</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِثْقَالَ</span><span class="en second ltr" dir="ltr">(equal to the) weight</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَرَّةٍ</span><span class="en second ltr" dir="ltr">(of) an atom</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَرًّا</span><span class="en second ltr" dir="ltr">evil,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَرَهُۥ</span><span class="en second ltr" dir="ltr">will see it.</span></span></span> <span class="verse-number"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></span></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

