<!doctype html>
<html class="no-js" lang="">
	<head>
		<title>Zabuun - Learn Arabic for English Speakers</title>
		<meta name="description" content="">
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/head.php';?>
	</head>
	<body>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/ie8.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/header.php';?>
		<div class="content">
			<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/side.php';?>
			<div class="main">
				<div class="location">
					<p class="breadcrumbs">Quran > At-Takwir</p>
				</div>
<div class="ayahs rtl" dir="rtl">
<p class="ayah 81-1 selected" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">When</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلشَّمْسُ</span><span class="en second ltr" dir="ltr">the sun</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُوِّرَتْ</span><span class="en second ltr" dir="ltr">is wrapped up,</span></span></span> <a href="#!/quran-wordbyword/81:1" class="ayahNumber" data-verse="5801"><span class="icon leftBracket"> </span>1<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-2" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنُّجُومُ</span><span class="en second ltr" dir="ltr">the stars</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱنكَدَرَتْ</span><span class="en second ltr" dir="ltr">fall, losing their luster</span></span></span> <a href="#!/quran-wordbyword/81:2" class="ayahNumber" data-verse="5802"><span class="icon leftBracket"> </span>2<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-3" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجِبَالُ</span><span class="en second ltr" dir="ltr">the mountains</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُيِّرَتْ</span><span class="en second ltr" dir="ltr">are moved away,</span></span></span> <a href="#!/quran-wordbyword/81:3" class="ayahNumber" data-verse="5803"><span class="icon leftBracket"> </span>3<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-4" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعِشَارُ</span><span class="en second ltr" dir="ltr">the full-term she-camels</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عُطِّلَتْ</span><span class="en second ltr" dir="ltr">(are) left untended;</span></span></span> <a href="#!/quran-wordbyword/81:4" class="ayahNumber" data-verse="5804"><span class="icon leftBracket"> </span>4<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-5" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْوُحُوشُ</span><span class="en second ltr" dir="ltr">the wild beasts</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">حُشِرَتْ</span><span class="en second ltr" dir="ltr">are gathered,</span></span></span> <a href="#!/quran-wordbyword/81:5" class="ayahNumber" data-verse="5805"><span class="icon leftBracket"> </span>5<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-6" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْبِحَارُ</span><span class="en second ltr" dir="ltr">the seas</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُجِّرَتْ</span><span class="en second ltr" dir="ltr">are made to overflow,</span></span></span> <a href="#!/quran-wordbyword/81:6" class="ayahNumber" data-verse="5806"><span class="icon leftBracket"> </span>6<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-7" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلنُّفُوسُ</span><span class="en second ltr" dir="ltr">the souls</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">زُوِّجَتْ</span><span class="en second ltr" dir="ltr">are paired,</span></span></span> <a href="#!/quran-wordbyword/81:7" class="ayahNumber" data-verse="5807"><span class="icon leftBracket"> </span>7<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-8" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمَوْءُۥدَةُ</span><span class="en second ltr" dir="ltr">the female infant buried alive</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُئِلَتْ</span><span class="en second ltr" dir="ltr">is asked</span></span></span> <a href="#!/quran-wordbyword/81:8" class="ayahNumber" data-verse="5808"><span class="icon leftBracket"> </span>8<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-9" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِأَىِّ</span><span class="en second ltr" dir="ltr">For what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذَنۢبٍ</span><span class="en second ltr" dir="ltr">sin</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">قُتِلَتْ</span><span class="en second ltr" dir="ltr">she was killed.</span></span></span> <a href="#!/quran-wordbyword/81:9" class="ayahNumber" data-verse="5809"><span class="icon leftBracket"> </span>9<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-10" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلصُّحُفُ</span><span class="en second ltr" dir="ltr">the pages</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نُشِرَتْ</span><span class="en second ltr" dir="ltr">are laid open,</span></span></span> <a href="#!/quran-wordbyword/81:10" class="ayahNumber" data-verse="5810"><span class="icon leftBracket"> </span>10<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-11" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلسَّمَآءُ</span><span class="en second ltr" dir="ltr">the sky</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كُشِطَتْ</span><span class="en second ltr" dir="ltr">is stripped away,</span></span></span> <a href="#!/quran-wordbyword/81:11" class="ayahNumber" data-verse="5811"><span class="icon leftBracket"> </span>11<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-12" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجَحِيمُ</span><span class="en second ltr" dir="ltr">the Hellfire</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">سُعِّرَتْ</span><span class="en second ltr" dir="ltr">is set ablaze,</span></span></span> <a href="#!/quran-wordbyword/81:12" class="ayahNumber" data-verse="5812"><span class="icon leftBracket"> </span>12<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-13" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَإِذَا</span><span class="en second ltr" dir="ltr">And when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجَنَّةُ</span><span class="en second ltr" dir="ltr">Paradise</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُزْلِفَتْ</span><span class="en second ltr" dir="ltr">is brought near,</span></span></span> <a href="#!/quran-wordbyword/81:13" class="ayahNumber" data-verse="5813"><span class="icon leftBracket"> </span>13<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-14" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلِمَتْ</span><span class="en second ltr" dir="ltr">Will know</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">نَفْسٌ</span><span class="en second ltr" dir="ltr">a soul</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَّآ</span><span class="en second ltr" dir="ltr">what</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَحْضَرَتْ</span><span class="en second ltr" dir="ltr">it has brought.</span></span></span> <a href="#!/quran-wordbyword/81:14" class="ayahNumber" data-verse="5814"><span class="icon leftBracket"> </span>14<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-15" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَلَآ</span><span class="en second ltr" dir="ltr">But nay!</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أُقْسِمُ</span><span class="en second ltr" dir="ltr">I swear</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْخُنَّسِ</span><span class="en second ltr" dir="ltr">by the retreating planets,</span></span></span> <a href="#!/quran-wordbyword/81:15" class="ayahNumber" data-verse="5815"><span class="icon leftBracket"> </span>15<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-16" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْجَوَارِ</span><span class="en second ltr" dir="ltr">Those that run</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْكُنَّسِ</span><span class="en second ltr" dir="ltr">(and) disappear,</span></span></span> <a href="#!/quran-wordbyword/81:16" class="ayahNumber" data-verse="5816"><span class="icon leftBracket"> </span>16<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-17" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلَّيْلِ</span><span class="en second ltr" dir="ltr">And the night</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَسْعَسَ</span><span class="en second ltr" dir="ltr">it departs,</span></span></span> <a href="#!/quran-wordbyword/81:17" class="ayahNumber" data-verse="5817"><span class="icon leftBracket"> </span>17<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-18" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَٱلصُّبْحِ</span><span class="en second ltr" dir="ltr">And the dawn</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِذَا</span><span class="en second ltr" dir="ltr">when</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَنَفَّسَ</span><span class="en second ltr" dir="ltr">it breathes</span></span></span> <a href="#!/quran-wordbyword/81:18" class="ayahNumber" data-verse="5818"><span class="icon leftBracket"> </span>18<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-19" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنَّهُۥ</span><span class="en second ltr" dir="ltr">Indeed, it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لَقَوْلُ</span><span class="en second ltr" dir="ltr">(is) surely a word</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَسُولٍ</span><span class="en second ltr" dir="ltr">(of) a Messenger</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">كَرِيمٍ</span><span class="en second ltr" dir="ltr">noble,</span></span></span> <a href="#!/quran-wordbyword/81:19" class="ayahNumber" data-verse="5819"><span class="icon leftBracket"> </span>19<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-20" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِى قُوَّةٍ</span><span class="en second ltr" dir="ltr">Possessor of power,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عِندَ</span><span class="en second ltr" dir="ltr">with</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِى ٱلْعَرْشِ</span><span class="en second ltr" dir="ltr">(the) Owner of the Throne</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مَكِينٍ</span><span class="en second ltr" dir="ltr">secure,</span></span></span> <a href="#!/quran-wordbyword/81:20" class="ayahNumber" data-verse="5820"><span class="icon leftBracket"> </span>20<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-21" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مُّطَاعٍ</span><span class="en second ltr" dir="ltr">One to be obeyed</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ثَمَّ</span><span class="en second ltr" dir="ltr">and</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَمِينٍ</span><span class="en second ltr" dir="ltr">trustworthy,</span></span></span> <a href="#!/quran-wordbyword/81:21" class="ayahNumber" data-verse="5821"><span class="icon leftBracket"> </span>21<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-22" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">صَاحِبُكُم</span><span class="en second ltr" dir="ltr">(is) your companion</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِمَجْنُونٍ</span><span class="en second ltr" dir="ltr">mad.</span></span></span> <a href="#!/quran-wordbyword/81:22" class="ayahNumber" data-verse="5822"><span class="icon leftBracket"> </span>22<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-23" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَلَقَدْ</span><span class="en second ltr" dir="ltr">And certainly</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَءَاهُ</span><span class="en second ltr" dir="ltr">he saw him</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِٱلْأُفُقِ</span><span class="en second ltr" dir="ltr">in the horizon</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْمُبِينِ</span><span class="en second ltr" dir="ltr">the clear.</span></span></span> <a href="#!/quran-wordbyword/81:23" class="ayahNumber" data-verse="5823"><span class="icon leftBracket"> </span>23<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-24" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُوَ</span><span class="en second ltr" dir="ltr">he (is)</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">عَلَى</span><span class="en second ltr" dir="ltr">on</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْغَيْبِ</span><span class="en second ltr" dir="ltr">the unseen</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِضَنِينٍ</span><span class="en second ltr" dir="ltr">a withholder.</span></span></span> <a href="#!/quran-wordbyword/81:24" class="ayahNumber" data-verse="5824"><span class="icon leftBracket"> </span>24<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-25" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُوَ</span><span class="en second ltr" dir="ltr">it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">بِقَوْلِ</span><span class="en second ltr" dir="ltr">(is the) word</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَيْطَـٰنٍ</span><span class="en second ltr" dir="ltr">(of) Shaitaan</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَّجِيمٍ</span><span class="en second ltr" dir="ltr">accursed.</span></span></span> <a href="#!/quran-wordbyword/81:25" class="ayahNumber" data-verse="5825"><span class="icon leftBracket"> </span>25<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-26" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">فَأَيْنَ</span><span class="en second ltr" dir="ltr">So where</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَذْهَبُونَ</span><span class="en second ltr" dir="ltr">are you going?</span></span></span> <a href="#!/quran-wordbyword/81:26" class="ayahNumber" data-verse="5826"><span class="icon leftBracket"> </span>26<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-27" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِنْ</span><span class="en second ltr" dir="ltr">Not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">هُوَ</span><span class="en second ltr" dir="ltr">it</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّا</span><span class="en second ltr" dir="ltr">(is) except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ذِكْرٌ</span><span class="en second ltr" dir="ltr">a reminder</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِّلْعَـٰلَمِينَ</span><span class="en second ltr" dir="ltr">to the worlds,</span></span></span> <a href="#!/quran-wordbyword/81:27" class="ayahNumber" data-verse="5827"><span class="icon leftBracket"> </span>27<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-28" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">لِمَن</span><span class="en second ltr" dir="ltr">For whoever</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">شَآءَ</span><span class="en second ltr" dir="ltr">wills</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">مِنكُمْ</span><span class="en second ltr" dir="ltr">among you</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">to</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَسْتَقِيمَ</span><span class="en second ltr" dir="ltr">take a straight way.</span></span></span> <a href="#!/quran-wordbyword/81:28" class="ayahNumber" data-verse="5828"><span class="icon leftBracket"> </span>28<span class="icon rightBracket"> </span></a></p>
<p class="ayah 81-29" style="font-family: 'KFGQPC Uthman Taha Naskh';"><span class=""><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">وَمَا</span><span class="en second ltr" dir="ltr">And not</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">تَشَآءُونَ</span><span class="en second ltr" dir="ltr">you will</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">إِلَّآ</span><span class="en second ltr" dir="ltr">except</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">أَن</span><span class="en second ltr" dir="ltr">that</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">يَشَآءَ ٱللَّهُ</span><span class="en second ltr" dir="ltr">Allah wills,</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">رَبُّ</span><span class="en second ltr" dir="ltr">Lord</span></span><span class="word staticWord"><span class="ar quranText top first rtl" dir="rtl">ٱلْعَـٰلَمِينَ</span><span class="en second ltr" dir="ltr">(of) the worlds.</span></span></span> <a href="#!/quran-wordbyword/81:29" class="ayahNumber" data-verse="5829"><span class="icon leftBracket"> </span>29<span class="icon rightBracket"> </span></a></p>
</div>

			</div>
		</div>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/footer.php';?>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/layout/scripts.php';?>
	</body>
</html>

